### ISSUE TITLE
Syntax highlighting like in The Racket Guide

### ISSUE THREAD

**Issue by mardukbp** [racket/drracket#11]
I am new to Racket and have been learning following The Racket Guide and coding in DrRacket (latest version in Linux). I find it frustrating that DrRacket does not color differently built-in functions and user-defined functions, neither built-in keywords like `empty` or `eof`. 

I would really like to have the kind of syntax highlighting that is used in the Racket Guide. I checked Color Schemes in the docs, but did not find any pointers to extend the syntax highlighting powers of DrRacket.

**Comment by rfindler** [comment]
Go to the preference dialog. Click on the "Colors" tab and then the "Racket" tab. Adjust the coloring of keywords. Then go to the "Editing" tab and inside that the "Indenting" tab and add new keywords that you want to be colored differently.

And please do visit the users mailing list if you have more questions like these: http://lists.racket-lang.org/
