### ISSUE TITLE
"Remove Unused Requires" refactoring doesn't handle `multi-in` forms correctly

### ISSUE THREAD

**Issue by dfeltey** [racket/drracket#110]
Running the "Remove Unused Requires" refactoring on this program:
```
#lang racket/base

(require racket/require)
(require (multi-in racket (list dict)))
first
```

produces:
```
#lang racket/base

(require racket/require)
(require)
first
```
Rather than just removing the `dict` part of the `multi-in` form.

**Comment by greghendershott** [comment]
Related: Dr Racket will color the entire `(multi-in racket (list dict))` form red as "unused" -- even though `list` is used. In an ideal universe only the `dict` portion would correctly be marked red as unused.

I actually first noticed this yesterday while consuming `syncheck:add-unused-require` items from `drracket/check-syntax` for Racket Mode, then went to DrR to cross-check its behavior.

---

I wonder if it would be pragmatic and reasonable to change `multi-in` to expand to one `(#%require)` form per module?  That's what `(require list dict)` would expand to, I think?

One the one hand drracket/check-syntax should ideally handle "everything". On the other hand if `multi-in` were from a third-party package, and its author learned there is a de facto, soft, unwritten protocol like this for tooling?  They would probably adapt `multi-in` to use it. At least as a mitigation until/unless the tooling improves and/or the protocol becomes formal.

**Comment by greghendershott** [comment]
It looks like `multi-in` currently expands to `combine-in`.

Using `combine-in` directly in the original source, also exhibits this bug.

`(combine-in racket/list racket/dict)` results in one big `$%require` form like this:

```racket
(#%require
 (just-meta 0 (rename racket/list filter-not filter-not))
 (just-meta 0 (rename racket/list list-prefix? list-prefix?))
 ...
 (just-meta 0 (rename racket/dict dict-set dict-set))
 (just-meta 0 (rename racket/dict dict-value-contract dict-value-contract))
 ... )
```
My guess is that any unused module path, like `racket/dict` in this case, will cause drracket/check-syntax to say that the _entire_ `#%require` is unused.

I bet it would not happen with `combine-in` expanding instead to:

```racket
(#%require
 (just-meta 0 (rename racket/list filter-not filter-not))
 (just-meta 0 (rename racket/list list-prefix? list-prefix?))
 ...)

(#%require
 (just-meta 0 (rename racket/dict dict-set dict-set))
 (just-meta 0 (rename racket/dict dict-value-contract dict-value-contract))
 ... )
```

**Comment by greghendershott** [comment]
Or maybe `combine-in` should be using `syntax/loc` on the pieces?

**Comment by greghendershott** [comment]
I opened PR #362 with an effort to fix this within `drracket/check-syntax`.
