### ISSUE TITLE
Website's (https://download.racket-lang.org/) connections are MitM'ed by Cloudflare

### ISSUE THREAD

**Issue by sp-1234** [racket/drracket#115]
1: go to https://download.racket-lang.org/
2: look at certificate info

> Issued To
> Common Name: sni88249.cloudflaressl.com

why this is a problem:
http://cryto.net/~joepie91/blog/2016/07/14/cloudflare-we-have-a-problem/
https://www.reddit.com/r/privacy/comments/41cb4k/be_careful_with_cloudflare/

it's even more bad because the website is used to serve executable downloads (and checksums of them), so Cloudflare could replace them both and regular users won't notice anything.

**Comment by samth** [comment]
The Racket web pages use Cloudflare as a CDN.  Note that the standard place to download the actual binaries, mirror.racket-lang.org, is not served via Cloudflare.
