### ISSUE TITLE
Notebook interface for DrRacket

### ISSUE THREAD

**Issue by mardukbp** [racket/drracket#12]
Coming from the IPython Notebook I really miss the user interface for interacting with and exploring this awesome language. I think a notebook GUI is much more productive and engaging than the current editor + REPL interface of DrRacket. Specially when considering the drawing and plotting capabilities of Racket, Maxima interaction, etc.

I do not know how difficult it would be to implement it, but I would appreaciate any pointers and hope that other users feel attracted to the idea.

**Comment by rfindler** [comment]
Thank you for your interest in DrRacket. I'm going to close this item as it isn't really an actionable request in a concrete way.

But let me point out that you might not yet have explored DrRacket enough. We do things differently than in python, but we can have all kinds of things in the interactions window. Try this program:

```#lang racket
(require plot)
(plot (function sin)
      #:x-min -10
      #:x-max 10)
```

**Comment by rfindler** [comment]
Also, you might consider posting these comments on the users mailing list instead of in the issue tracker. You will get better feedback: http://lists.racket-lang.org/

**Comment by mardukbp** [comment]
My apologies for not using the mailing list. I guess I will try to implement a notebook interface in emacs. Thank you.

**Comment by rfindler** [comment]
Check out `racket-mode` in Emacs. It has lots of the things that DrRacket has, but in the familiar Emacs setting. https://github.com/greghendershott/racket-mode

**Comment by mardukbp** [comment]
Thank you! It looks great.
