### ISSUE TITLE
Patch for Mac OS 10.12.5 “Search in help desk” links has weird behavior

### ISSUE THREAD

**Issue by mbutterick** [racket/drracket#127]
Apparently the 10.12.5 update [introduced a bug](http://www.andrewjaffe.net/blog/2017/05/python-bug-hunt.html) in `osascript` that means it can no longer find the default web browser with `open location`. In DrRacket, this means that using the “Search in help desk” option produces an error like this:

```
browser-run: process execute failed: '(#<path:/usr/bin/osascript> "-e" 
"open location \"file:///Users/···/Library/Racket/6.9.0.1/doc/search/index.html?q=provide\"")
```

FYI, in case others experience the behavior. Since it’s inarguably an OS bug, this is not a call to action :wink:

**Comment by stamourv** [comment]
Do you still see this error in the nightly builds?
This looks like a bug we added a workaround for a few weeks ago.

**Comment by mbutterick** [comment]
You are correct. The bug does not manifest in the current build.

**Comment by mbutterick** [comment]
FWIW the patch exhibits some odd behavior. If my Mac OS Chrome is open, the SIHD link is opened there. If not, then the SIHD link is opened in Chrome on my Windows virtual machine.

**Comment by rfindler** [comment]
What is SIHD? 

It may be that that's just what "open" does. You can run the osascript command-line directly in the terminal window? The precise command is here:

https://github.com/racket/racket/blob/ffe07718b8cf0663402ae61c55d4ba05ff0e9ae7/pkgs/net-lib/net/sendurl.rkt#L165

but what it is doing is roughly:

```
osascript -e 'tell application "Chrome" to open location "<someurl>" activate
```

If you know of a different argument to pass, maybe we can change it?

**Comment by mbutterick** [comment]
SIHD = Search in Help Desk

I think it’s too edge-casey to bother with. Apparently [the workaround](https://apple.stackexchange.com/a/158864) (to the workaround … to the underlying OS bug) is to specify the full path to the application (e.g., `/Applications/Google Chrome.app`) rather than just `Chrome`.
