### ISSUE TITLE
DrRacket 6.9 Crashes Windows 10

### ISSUE THREAD

**Issue by d223chen** [racket/drracket#128]
DrRacket will start and then I can usually interact with it for a minute before it crashes my computer.

My Windows 10 sends me this error:
"UNEXPECTED_KERNEL_MODE_TRAP"

every time.

**Comment by mflatt** [comment]
Thanks for the report! We have prepared a workaround for this bug (which is in Windows, not DrRacket) for the next release, and you can try out the current snapshot. See racket/racket#1671 for more information and a link to the snapshot builds.
