### ISSUE TITLE
Highlighting in Interactions only partially applied

### ISSUE THREAD

**Issue by gfbee** [racket/drracket#129]
It only gets applied to the first of a parenthesized s-expression, recursively:

![image](https://user-images.githubusercontent.com/4381135/28442841-82e26658-6d80-11e7-9ace-c8fcb5da5e02.png)

**Comment by rfindler** [comment]
Maybe you have the setting turned on that does that? Try changing the paren
highlighting in the preferences dialog.

Robby

**Comment by gfbee** [comment]
The problem is that it's not being applied uniformly. Here's a fully-symmetric example expression, that gets highlighted asymmetrically in the Interactions:

![image](https://user-images.githubusercontent.com/4381135/28443269-06e4c89a-6d83-11e7-93e1-dc5c3121bb7d.png)

But in the Definitions:

![image](https://user-images.githubusercontent.com/4381135/28443325-50d8368a-6d83-11e7-959e-4ad1a2a44c27.png)

**Comment by gfbee** [comment]
It's the space that seems to be interfering somehow. These all get shaded differently:
```
((abc)   (abc)   (abc))
((abc)(abc)      (abc))
((abc)      (abc)(abc))
```
