### ISSUE TITLE
Background expansion error for duplicate identifiers shows expanded code

### ISSUE THREAD

**Issue by justinpombrio** [racket/drracket#134]
This program:

    (define x 1)
    (define x 2)

produces the following error message in the background expansion region:

    unsaved editor:4:8: module: duplicate definition for identifier at: x in: (define-values (x) 2)

This should not mention (define-values (x) 2), as that is expanded code that should remain hidden. The message should instead refer to the original source, or to nothing at all.

In contrast, if you hit the "run" button, then the error message displayed does not mention the expanded code. So this issue seems specific to DrRacket's background expansion. (For this reason I'm guessing that it's a DrRacket issue, though it could also be a Racket issue.)

**Comment by rfindler** [comment]
I think you have it backwards; DrRacket is asking racket to not include the source in its syntax error messages in Run mode. Online expansion is running in a more vanilla mode where you get somethign close to what you get in the REPL:

```
$  racket -q
Welcome to Racket v6.10.0.2.
> (module m racket/base (define x 1) (define x 2))
stdin::36: module: duplicate definition for identifier
  at: x
  in: (define-values (x) 2)
  context...:
   /Users/robby/git/exp/plt/racket/collects/racket/private/misc.rkt:88:7
> 
```

So I guess that you probably want a change made to how `define` (or perhaps definition contexts, I'm forgetting where this check exactly is) works.

**Comment by justinpombrio** [comment]
Ah, yes, in retrospect it makes sense that the background check is more vanilla and the foreground error message is the one that DrRacket modifies. Sorry, will move this to the Racket repo.

**Comment by rfindler** [comment]
FWIW, DrRacket just asks the error message to not include the source text. There is a parameter for this but I cannot for the life of me remember its name. But DrRacket isn't modifying the error message per se; just flipping a flag that the error message construction code looks at. (DrRacket turns it on because it knows it can highlight the source location.)
