### ISSUE TITLE
another DrRacket Internal Error

### ISSUE THREAD

**Issue by AlexKnauth** [racket/drracket#14]
I get DrRacket Internal Error boxes like this every once it a while:
```
interval-map-cons*!: bad interval: start 14255 not less than end 14255
  context...:
   /Applications/Racket/2015-08-15/Racket v6.2.900.10/share/pkgs/data-lib/data/interval-map.rkt:66:0: interval-map-cons*!
   /Applications/Racket/2015-08-15/Racket v6.2.900.10/share/pkgs/drracket/drracket/private/syncheck/gui.rkt:855:12: syncheck:add-arrow/name-dup/pxpy method in ...ate/syncheck/gui.rkt:365:10
   /Applications/Racket/2015-08-15/Racket v6.2.900.10/share/pkgs/drracket/drracket/private/syncheck/gui.rkt:1922:10: loop
   /Applications/Racket/2015-08-15/Racket v6.2.900.10/share/pkgs/gui-lib/framework/private/logging-timer.rkt:41:0: log-timeline/proc
   /Applications/Racket/2015-08-15/Racket v6.2.900.10/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:454:6
   /Applications/Racket/2015-08-15/Racket v6.2.900.10/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:505:32
   /Applications/Racket/2015-08-15/Racket v6.2.900.10/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:653:3
```

**Comment by rfindler** [comment]
Do you see these errors always with the two numbers the same, or with the start number smaller than the end number?

Also, I've pushed a change to that error message that will hopefully tell me where the bad interval is coming from (that is, lots of bits information come from different places into that function and get stuck in an interval map and the `to-add` argument should tell us which one).

**Comment by samth** [comment]
I can provoke this error (with the numbers different) pretty consistently by opening up `racket/unit.rkt` and just scrolling up and down (with the arrow keys) until the error happens.

**Comment by samth** [comment]
Here's the new extra info from that method:

```
interval-map-cons*!: from is not strictly less than to
  im: #<interval-map>
  start: 95984
  end: 95984
  obj: (var-arrow #0=(object:...ivate/get-extend.rkt:133:12 ...) 959...
  context...:
   /home/samth/sw/plt/extra-pkgs/data/data-lib/data/interval-map.rkt:67:0: interval-map-cons*!
   /home/samth/sw/plt/extra-pkgs/drracket/drracket/drracket/private/syncheck/gui.rkt:855:12: syncheck:add-arrow/name-dup/pxpy method in ...ate/syncheck/gui.rkt:365:10
   /home/samth/sw/plt/extra-pkgs/drracket/drracket/drracket/private/syncheck/gui.rkt:1922:10: loop
   /home/samth/sw/plt/extra-pkgs/gui-lib/gui-lib/framework/private/logging-timer.rkt:41:0: log-timeline/proc
   /home/samth/sw/plt/extra-pkgs/gui-lib/gui-lib/mred/private/wx/common/queue.rkt:454:6
```

**Comment by rfindler** [comment]
Thanks, this was helpful. I see how I need to fix check syntax.

But meanwhile, it appears that syntax-parse is trying to draw an error that
starts at the position just before :import-clause/contract and just after
the paren that preceeds it on line 1940 of racket/unit.rkt to the
occurrence of "i.c" on line 1964.

Is that also a syntax-parse bug?

**Comment by rfindler** [comment]
Fixed: https://github.com/racket/drracket/commit/f347a8b8f6cade91762d9291a1cd5efaad045d90

**Comment by samth** [comment]
@rmculpepper for the syntax-parse issue.

**Comment by AlexKnauth** [comment]
I wonder if that could possibly have been be caused by: 
https://github.com/plt/racket/commit/3c5ed5d8e12c8c28715be69454e19909c1a01704
