### ISSUE TITLE
UI unresponsive when sending many tooltips via a logger to Background Check Syntax

### ISSUE THREAD

**Issue by david-christiansen** [racket/drracket#142]
# Summary
While Check Syntax is creating tooltips, the DrRacket UI becomes unresponsive. This leads to sluggish editor performance while working with macros that provide lots of tooltip feedback.

# To reproduce:
1. Open the attached file in DrRacket
2. Ensure that the Check Syntax tool and background expansion are enabled
3. Make some kind of edit in the file (for example, adding a space to the end of a line)
4. While the dot in the lower right corner of DrRacket is blue, attempt to scroll up and down

# Expected behavior:
Scrolling and/or editing works as usual while the dot is blue

# Observed behavior:
The UI pauses while the dot is blue, and "catches up" after the tooltips have been calculated.

# Test program
```racket
#lang racket

(require (for-syntax syntax/srcloc))

(begin-for-syntax
  (define-logger online-check-syntax)
  
  (define (save-tooltip msg where)
    (define start (sub1 (source-location-position where)))
    (define end (+ (sub1 (source-location-position where))
                 (source-location-span where)))
    (for ([i (in-range start end)])
        (define tooltip
          (vector where
                  i
                  (add1 i)
                  (lambda () (format "~s: ~s" (msg) i))))
      (log-message online-check-syntax-logger
                   'info
                   "tooltip"
                   (list (syntax-property #'(void)
                                          'mouse-over-tooltips
                                          tooltip))))))

(define-syntax (self-tooltip stx)
  (save-tooltip (lambda () (format "Source: ~a" (syntax->datum stx))) stx)
  (syntax-case stx ()
    [(_ e) #'e]))

(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3)) 
(void (self-tooltip 3))
 
```

**Comment by david-christiansen** [comment]
Interestingly, this doesn't seem to occur when the tooltips are added via a syntax property rather than through log messages (as recommended in the section of the documentation on [Cooperating with Background Check Syntax](https://docs.racket-lang.org/tools/Cooperating_with_Background_Check_Syntax.html)).

Here's an alternative tooltip-spammer that doesn't slow down the UI thread on my machine. Also, the blue dot is only visible for a fraction of a second, instead of for multiple seconds.
```racket
#lang racket

(require (for-syntax syntax/srcloc))

(begin-for-syntax

  (define (add-tooltip where msg stx)
    (define start (sub1 (source-location-position where)))
    (define end (+ (sub1 (source-location-position where))
                   (source-location-span where)))
    (syntax-property stx
                     'mouse-over-tooltips
                     (for/list ([i (in-range start end)])
                       (vector where
                               i
                               (add1 i)
                               (lambda () (format "~s: ~s" (msg) i)))))))



(define-syntax (self-tooltip stx)
  (syntax-case stx ()
    [(_ e)
     (add-tooltip stx
      (lambda () (format "Source: ~a" (syntax->datum stx))) #'e)]))

(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3)) 
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3)) 
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3))
(void (self-tooltip 3)) 
(void (self-tooltip 3))
 
```

**Comment by rfindler** [comment]
The commit I just pushed improves the situation a little bit, but a better fix would be to make `syncheck:update-drawn-arrows` actually do what its name says it does (which would probably reveal there are some other things that need updating and improving in similar kinds of computations), or somehow detect that there are multiple separate traces coming in and waiting for the last one before finishing each one.

In any case, DrRacket now lets you at least edit a little bit (it is still too sluggish in this situation, tho).

**Comment by david-christiansen** [comment]
I finally figured out how to get the Git version of DrRacket to run, and this goes much, much faster. Not only does it never freeze, the blue dot period has dropped from seconds to well under a second in duration. I'll go test with the actual programs that I care about, but as far as I'm concerned, this is fixed.

Thanks for the prompt attention!

**Comment by rfindler** [comment]
I think this probably shouldn't be closed, as the fix I pushed isn't really the right one.

**Comment by rfindler** [comment]
Alright, I closed this one. I don't see any (new) problems with the change I made. Probably it will be slightly zippier for you @david-christiansen because with the old commit, it would only occasionally run the expensive computation and I think it doesn't ever do it now.

That expensive computation was refreshing the entire screen, so with this commit there may well be bugs of the form "this thing wasn't redrawn automatically when the little circle turned green", so if you see those, please holler.

**Comment by david-christiansen** [comment]
Thanks very much! Even with the partial fix, things were zippy enough for me, but I appreciate the desire to do the Right Thing here.
