### ISSUE TITLE
History in interaction mode

### ISSUE THREAD

**Issue by sidkshatriya** [racket/drracket#145]
When I use DrRacket, the interaction mode seems to lack some basic abilities like history. How can I get history on the racket repl while in DrRacket? (i.e. when I press the up arrow I should be able to get the previous command and so forth)

**Comment by rfindler** [comment]
In the "Edit" menu, select the "Keybindings" > "Show Active Keybindings..." menu item and look for "put-previous-sexp" to see what key it is bound to. (On a mac, it is control-up).
