### ISSUE TITLE
DrRacket colour theme text alignment difference

### ISSUE THREAD

**Issue by bhrgunatha** [racket/drracket#151]
I wrote my own [dark DrRacket colour theme](https://pastebin.com/vfdmWF0d) and installed it and it seems to work.

Except for one extremely bizarre [text alignment issue](http://i.imgur.com/1zFqMfr.png) with `cond`, `let` and similar forms with nested lists as the second element.

Notice the upper image aligns perfectly but the lower image (my dark theme) is slightly misaligned.
Both images use the same fixed width font. All other colour themes I've tried align correctly.
- If the first branch is on the same line as `cond` it gets pushed slightly to the right and the remaining lines look correctly aligned.
- If the first branch is on a separate line then they all align correctly.

It's a very minor thing but it really bugs me.
How can a colour them cause the text to align differently?
Any ideas what is wrong?

**Comment by iitalics** [comment]
It looks to me like the bold text is causing the characters to no longer be fixed width

**Comment by bhrgunatha** [comment]
It seems when a fixed width font is bold the width is slightly bigger than the regular width. I thought they would be the same since it's a fixed width font. Racket layout is different special because I set bold keywords in several environments/languages and only ever noticed it in DrRacket.
