### ISSUE TITLE
Single line comments loose their coloring after tests are run

### ISSUE THREAD

**Issue by jhalaa** [racket/drracket#158]
When I write lambda functions and add comments to those functions,
they are colored brownish and are similar to other single lined comments. However, once I run the tests, These comments turn black and loose their coloring. The below are the screenshots.

![screen shot 2017-10-30 at 12 31 30 pm](https://user-images.githubusercontent.com/13657344/32191460-68f22d44-bd6e-11e7-8318-5216985d978d.png)
![screen shot 2017-10-30 at 12 31 03 pm](https://user-images.githubusercontent.com/13657344/32191438-585eb8d0-bd6e-11e7-9b36-acefe70ada04.png)

**Comment by rfindler** [comment]
This is the test coverage results from DrRacket and is intentional. It means that part of the program was not run by the tests.
