### ISSUE TITLE
font-picking logic in DrRacket is strange

### ISSUE THREAD

**Issue by mbutterick** [racket/drracket#16]
When you pick a font family in the DrRacket preferences box, it seems that DrRacket chooses as its default style the first style in the family that designates its weight as 400 or more. The problem is that not every monospaced family has a 400 weight. For instance, my Triplicate family starts at 300. Source Code Pro is another. When you select one of these families, DrRacket skips over the base style (because it has a weight less than 400) and defaults to the bold style instead (which reliably has a weight greater than 400). 

<img width="824" alt="screen shot 2015-09-04 at sep 04 10 09 09 am" src="https://cloud.githubusercontent.com/assets/1425051/9689957/47c6ed86-52ee-11e5-8241-6b6753056bb1.png">
<img width="828" alt="screen shot 2015-09-04 at sep 04 10 09 23 am" src="https://cloud.githubusercontent.com/assets/1425051/9689958/48cdec2a-52ee-11e5-8fae-d8e46df24c97.png">

The only exception to this behavior is if the font does not have a 400+ weight installed, in which case DrRacket will use the light style. Here, I’ve disabled the bold styles in Source Code Pro, and now it selects the light style:

<img width="826" alt="screen shot 2015-09-04 at sep 04 10 19 12 am" src="https://cloud.githubusercontent.com/assets/1425051/9689988/775a7c8e-52ee-11e5-9f27-ae73eeab8116.png">

I think the second case should be the preferred behavior: that DrRacket should use as its default the lightest weight available of the font family, not the first one that has weight 400+.

(Another approach would be to add a “default weight” popup picker underneath “Font Name” in the preferences dialog, but that’s an extra moving part.)

**Comment by rfindler** [comment]
I think this is actually a `racket/gui` PR. @mflatt ?

**Comment by mflatt** [comment]
Yes. And/or `racket/draw`. Or Pango, but probably we can do something at the `racket/draw` or `racket/gui` level.

**Comment by mflatt** [comment]
After a closer look, I'm not sure what should change here.

The rule that the default weight is 400 or more comes from Pango. The general font-selection dialog does offer a "light" option, which makes the light variations accessible at that level. That font-selector dialog is restricted to three weights ("default", "light", and "bold"), and think other weights would be accessible only by string encoding as a "face"; the accessibility of more than 3 weights doesn't seem to be the issue here, though.

Overall, I'm reluctant to change or override the name-to-font selection mechanism that comes from Pango, which would be the only way to make DrRacket's dialog as-is to pick light fonts. Besides changing the DrRacket dialog to include a "weight" choice, there are other possibilities, such as populating either the popup menu or the "Other..." dialog with `(get-face-list #:all-variants? #t)`.

**Comment by rfindler** [comment]
While we're on the subject of this dialog, why don't the Triplicate fonts
show up in the result of `(get-face-list 'mono)`?

**Comment by rfindler** [comment]
I think adding a weight checkbox is probably the best option so far.
It seems to work reasonably well for Triplicate because it changes the
font of the other text in the DrRacket interactions window in what
seems like a matching way.

**Comment by rfindler** [comment]
Okay, I pushed the weigh choice% addition: https://github.com/racket/drracket/commit/ac7556b8c3301d50fd59331294321d2879b8f421

**Comment by mbutterick** [comment]
What would be the downside of showing all the individual styles (IIU your proposed solution C)?

**Comment by rfindler** [comment]
I could do that too, but that is less accessible.

**Comment by mbutterick** [comment]
Fair enough. Thanks Robby.

**Comment by rfindler** [comment]
Do we know why triplicate doesn't appear to be a fixed width font to drr?

**Comment by mbutterick** [comment]
Where are you noticing this issue? All the Triplicates show up on my DrRacket font menu (OS X 10.9.5):

<img width="835" alt="screen shot 2015-09-05 at sep 05 6 24 46 pm" src="https://cloud.githubusercontent.com/assets/1425051/9701955/6832a412-53fb-11e5-98ba-9915bc18af16.png">

**Comment by rfindler** [comment]
I am using 10.10.4, but I'm not sure if that's what makes the difference. I see this:

```
> (get-face-list 'mono)
'("Andale Mono"
  "Apple Color Emoji"
  "Courier"
  "Courier New"
  "Inconsolata"
  "Latin Modern Mono"
  "Latin Modern Mono Caps"
  "Latin Modern Mono Light"
  "Latin Modern Mono Light Cond"
  "Latin Modern Mono Prop"
  "Latin Modern Mono Prop Light"
  "Latin Modern Mono Slanted"
  "Menlo"
  "Monaco"
  "Monospace"
  "Osaka"
  "PCMyungjo"
  "PT Mono"
  "TeX Gyre Cursor")
> (filter (λ (x) (regexp-match? #rx"Trip" x))
          (get-face-list))
'("Triplicate C3"
  "Triplicate C3c"
  "Triplicate C3p"
  "Triplicate C3s"
  "Triplicate C4"
  "Triplicate C4c"
  "Triplicate C4p"
  "Triplicate C4s"
  "Triplicate T3"
  "Triplicate T3c"
  "Triplicate T3p"
  "Triplicate T3s"
  "Triplicate T4"
  "Triplicate T4c"
  "Triplicate T4p"
  "Triplicate T4s")
```

**Comment by mflatt** [comment]
The "Triplcate"s show up in the list for me on 10.10.5.

**Comment by mflatt** [comment]
Is it possible that Robby and I have different versions of the Triplicate font? I recall installing it later than Robby.

**Comment by rfindler** [comment]
Can you remind us the predicate that 'mono uses?

**Comment by mbutterick** [comment]
I think it’s looking for the Panose monospaced bit, which was initially wrong and not fixed until Jan 2015. So yes, could well be versionitis. I’ll send you a new set.

**Comment by rfindler** [comment]
Thanks, that was it!

**Comment by mbutterick** [comment]
BTW the new “Weight” picker works nicely. Thanks.

**Comment by mbutterick** [comment]
Though FWIW the “Weight” setting does not carry through to the “Color Schemes” panel

<img width="827" alt="screen shot 2015-09-09 at sep 09 1 02 36 pm" src="https://cloud.githubusercontent.com/assets/1425051/9772750/0e87b25e-56f3-11e5-8fc7-ca1c354799f4.png">

**Comment by rfindler** [comment]
Okay, I fixed that with
https://github.com/racket/gui/commit/e5cb582ed552a309660d23dc72b8a6af6abc24dd

The change I made won't affect your version of DrRacket unless you delete
your preferences. You could selectively delete just some of the lines in
the file. I think it suffices to delete all of the lines that have
"color-scheme-entry" in them, but I had a little trouble getting it right
myself when I was testing.

Also note that this affects not just the preferences dialog, but the actual
color schemes too. Exactly how is a bit subtle, but it can affect the
content of the DrRacket editor.
