### ISSUE TITLE
add script-plugin to DrRacket as part of the Racket Distribution

### ISSUE THREAD

**Issue by spdegabrielle** [racket/drracket#168]
add [script-plugin](https://pkgs.racket-lang.org/package/script-plugin) to DrRacket - script-plugin is awesome. 

The DrRacket Plugins system is more powerful, but this is easier and can still do a lot.

**Comment by spdegabrielle** [comment]
closed in error I still think this is a good idea. 

I'm wondering what the criteria is to make a package part of the main distribution?

**Comment by bennn** [comment]
I don't think there's an official protocol. But someone would need to make a pull request to `racket/racket` adding `script-plugin` and documentation --- so that's probably the best place to start.

**Comment by spdegabrielle** [comment]
Thank you!
