### ISSUE TITLE
Package installation pop-up should strip trailing spaces

### ISSUE THREAD

**Issue by florence** [racket/drracket#17]
When installing a package via 'File -> Install Package' a leading or trailing space can cause the install to fail (e.g. ' http://file' vs 'http://file'). This is non-obvious and has been confusing some students.

Could the prompt strip leading or trailing spaces?

**Comment by rfindler** [comment]
Are pkgs allowed to have spaces in their names?

**Comment by florence** [comment]
No. From the docs: "a package name — a string made of the characters a through z, A through Z, 0 through 9, _, and -." (see http://docs.racket-lang.org/pkg/Package_Concepts.html)

**Comment by rfindler** [comment]
Then we probably want to strip spaces and have the field turn pink or
something when there are bad chars in it. (The dialog you're talking about
is not actually in DrRacket, it's in the pkg manager.)

**Comment by florence** [comment]
Oh! okay, Moving this issue there.
