### ISSUE TITLE
libunique is going away; how to keep single instance support?

### ISSUE THREAD

**Issue by bremner** [racket/drracket#182]
Apparently the next release of Debian stable won't have libunique in it

   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885816

I suppose this will become a problem other places as well.  Do you have any plans to support single-instance support in some other way? I at least find the single-instance support handy.

**Comment by mflatt** [comment]
DrRacket uses libunique only for GTK+ 2. As long as GTK+ 3 is available, single-instance support will continue to work without libunique.
