### ISSUE TITLE
Color schemes can't change window border and panel separator colors

### ISSUE THREAD

**Issue by jackfirth** [racket/drracket#183]
For example, when using the "White on Black" color scheme:

<img width="1436" alt="screen shot 2018-01-03 at 1 30 19 pm" src="https://user-images.githubusercontent.com/8175575/34540699-5b6f84ce-f08a-11e7-8010-3151ff89b447.png">

This makes "dark editor" color schemes less pleasant to use, since the high contrast is a bit painful on the eyes.

**Comment by rfindler** [comment]
That border is actually a scrollbar! I guess it is drawn by the OS, so probably fixing this involves changes to `racket/gui`.

**Comment by rfindler** [comment]
This one looks fixed these days.
