### ISSUE TITLE
find/replace with `σ` inserts `\sigma`

### ISSUE THREAD

**Issue by florence** [racket/drracket#187]
To reproduce:

in the file
```
#lang racket
test
```
hit cmd-f, and enter `test` in the find box. In the replace box type `\sigma` then `ctrl-\` to get `σ`.
Hit "next" then "replace". The buffer now has `\sigma` in it instead of `σ`. This doesn't happen if I insert a `σ` directly into the replace field.

**Comment by rfindler** [comment]
These instructions do not produce the promised result when I follow them. I get σ.

**Comment by florence** [comment]
Hrm, I can't reproduce now either. I'll keep an eye out for it showing up again!
