### ISSUE TITLE
-singleInstance seems not to be working

### ISSUE THREAD

**Issue by bremner** [racket/drracket#191]
Running DrRacket twice with -singleInstance is starting two gracket processes

> % ps x | grep Instance
>   621 pts/2    Sl     0:07 /usr/lib/racket/gracket -singleInstance -N /usr/bin/drracket -J DrRacket -l- drracket/drracket.rkt /home/bremner/foo.rkt
>   644 pts/2    Sl     0:10 /usr/lib/racket/gracket -singleInstance -N /usr/bin/drracket -J DrRacket -l- drracket/drracket.rkt /home/bremner/bar.rkt

This is on Debian (I tested 6.11 and 6.12); I had a report of similar behaviour on Arch Linux.

At least in my case libunique-1.0 is installed, although I believe drracket will print an error at startup if it is not and -singleInstance is used

**Comment by mflatt** [comment]
libunique matters only when using GTK+ 2. With (the default) GTK+ 3, linunique isn't needed.

I've pushed a repair to the "gui-lib" package that I hope will solve this problem on your machine: racket/gui@046a0fb98915b828d5704505ecad547059a16ca9

**Comment by bremner** [comment]
Matthew Flatt <notifications@github.com> writes:

> Looks like I mangled that commit, so that it didn't get all the needed
> pieces. I've pushed another commit to add the call to
> `g_application_register`.

Yes, that seems to fix it, thanks!

d
