### ISSUE TITLE
Possible problem with documentation help pop-in

### ISSUE THREAD

**Issue by abmclin** [racket/drracket#192]
I'm not sure if this is a bug or expected behavior but it's odd and not intuitive to me.

It concerns the documentation help pop-in that can be found in the upper right corner of DrRacket's window. I don't know what its official name is feel free to enlighten me on the correct name.

The help pop-in seems to update its presented documentation based on what I just typed in though this doesn't appear to have any clear pattern to it. It sometimes updates and sometimes it doesn't change.

I had been thinking it would be nice if the pop-in updates based on which identifier I click on since this would be more useful, so I asked on Slack on whether if that was possible. I was told that yes the pop-in does show documentation based on where I placed the text caret or typed in. 

This doesn't happen to me, then I discovered that when you click the lock icon to keep the pop-in open, clicking on identifiers does update the documentation content in the pop-in. Updating doesn't happen when the pop-in is in the collapsed state.

This is odd behavior to me, I would have expected the pop-in to update its content regardless of whether it's in the locked or collapsed state. So I'm reporting this as a new issue. Even if it's not technically a bug, it would be preferable to have the pop-in update its content independent of its visibility state.

If you are in agreement this should be fixed, I'd be happy to take a look at the code and see what I can do to repair this.

**Comment by rfindler** [comment]
Can you perhaps illustrate what you mean with a small series of steps (and what you expected and how it is different than what you see)? I'm not sure I'm getting the point.

**Comment by abmclin** [comment]
Yes gladly, I'll prepare some screenshots.

**Comment by rfindler** [comment]
I think I'd probably be able to understand with just a series of steps and a description of what's wrong with the final result.

**Comment by abmclin** [comment]
I've attached a PDF with screenshots and accompanying commentary.

[DrRacket Documentation Help Pop-In Issue Explanation.pdf](https://github.com/racket/drracket/files/1707790/DrRacket.Documentation.Help.Pop-In.Issue.Explanation.pdf)

**Comment by abmclin** [comment]
I discovered another case where the documentation pop-in does not update as expected. This is a different case from the above and I've attached another PDF showing how to reproduce it.

[DrRacket Documentation Help Pop-In Issue Number 2 Explanation.pdf](https://github.com/racket/drracket/files/1707928/DrRacket.Documentation.Help.Pop-In.Issue.Number.2.Explanation.pdf)
