### ISSUE TITLE
Disabling keybindings for overwrite mode

### ISSUE THREAD

**Issue by soegaard** [racket/drracket#2]
Scenario:
   - overwrite mode is active in the editor
   - overwrite keybindings is disabled in preferences

No the editor is stuck in overwrite mode.

Suggestion: Disabling the keybindings should also turn off overwrite mode in the editor.

**Comment by rfindler** [comment]
Thanks. I've done that wit this commit:  https://github.com/racket/gui/commit/d1e3a991cdeb4e461ab6272d15a0ac13ee17cc58
