### ISSUE TITLE
Feature request: automatically delete closing parens of empty s-expressions when automatic parentheses are enabled

### ISSUE THREAD

**Issue by lexi-lambda** [racket/drracket#201]
I use DrRacket’s “Enable automatic parentheses” feature to automatically insert closing parens when I type opening ones, which I quite like. However, there is one small infelicity about it that I think would be nice if it were changed. Sometimes, I will accidentally type an open paren, then realize I actually did not want it after all. I delete the open paren, but this leaves a dangling close paren—the one automatically inserted by DrRacket—that I must manually delete. This is especially awkward since it is after my cursor, and I must either use forward-delete or the cursor keys to remove it.

Instead, I’d appreciate it if, when automatic parentheses are enabled, DrRacket would delete both parentheses when the open paren is deleted in the text `()`. This would prevent the dangling parens.

Also, for what it’s worth, other editors implement this behavior, such as Atom (via the built-in bracket-matcher plugin, which is enabled by default) and Vim (with the commonly-used autoclose plugin, which is the equivalent of DrRacket’s automatic parentheses mode).

**Comment by rfindler** [comment]
Is it better to always delete the close when the open is deleted, or only
when it is an empty sexp?

Robby

**Comment by lexi-lambda** [comment]
I think it should only delete the close paren when it is an empty s-exp. That’s what the other editors I listed do, so they probably do it that way for a reason, and it’s probably better for consistency. If it deleted all matching parens whenever a paren was deleted, that would be interesting, but I think that’s pretty dramatically different from what automatic parentheses currently does.

**Comment by rfindler** [comment]
Okay. The other question is: does it do this only when one types the delete key, or when the paren is deleted by any means? (cmd/ctl-x or who knows what other myriad ways there are to delete things)

**Comment by lexi-lambda** [comment]
Anecdotally, in both Atom and vim, it *only* happens when the user deletes the open paren using the backspace key. If they delete it any other way, including forward-delete or vim normal-mode keybindings (including if using vim-mode in Atom), it doesn’t delete the close paren.

Does this behavior make sense? I don’t know, but it is the most conservative. Personally, I think it’s reasonable, since it means it really only happens when the user makes a mistake—if they type `(` then immediately type backspace—and it’s unlikely to get triggered otherwise (since users will either press backspace repeatedly when to the right of the close paren, deleting it before the open paren, or they will press forward-delete repeatedly when to the left of the open paren, and they won’t have to do any mental gymnastics to calculate exactly how many forward-delete presses they must omit to deal with the auto-deleted close parens).

**Comment by jbclements** [comment]
+1 to everything in this discussion, especially the use of the word “infelicity.”

John

**Comment by bzyeung** [comment]
I'm interested in taking a crack at this, but I think there's at least one more thing to clarify: since DrRacket does not add close parens in comments and strings, I'm assuming we also want this to *not* remove the close paren in those contexts.  That is, we only want to remove the close paren in contexts where typing the open paren would have auto-inserted the close paren, right?

Also, do we want this to exhibit the same behavior for the other automatically added characters `"` and `|`?  (Should I create a separate issue for that?)

**Comment by rfindler** [comment]
The thing to look into is the syntax colorer. It is tracking various information about where strings and parens are. Then a layer on top of it matches parentheses, and then the keybindings can use that information to do various things.

**Comment by bzyeung** [comment]
Since we only wanted it to do this when using the backspace key, the approach I had in mind was to add a new keybinding for `~c:backspace` that uses information from the syntax colorer to determine whether to remove the (immediately following) matching close paren.  Is that a bad approach?

As far as I can tell, matching `"` and `|` are handled as a separate case in the paren-inserting function.  I think those would be easy enough to add to the removal, but I just wanted to make sure that was the desired behavior.

**Comment by bzyeung** [comment]
I saw that that DrRacket documentation update got merged for this, but not the implementation code (which was in `racket/gui`).  Has that feature been reviewed?  I tried to err on the side of conservative regarding its treatment of double quotes.  My apologies; I meant to solicit opinions but got pulled onto other things.

Separately, Is there a better way to tie together commits in different repositories?

**Comment by rfindler** [comment]
Oh, I'm sorry! Lets see if we can get the other ones sorted out to make the docs update here is correct. (I don't know of a better way.)

[This pull request?](https://github.com/racket/gui/pull/162)

**Comment by bzyeung** [comment]
Yep, that's the one!

**Comment by Metaxal** [comment]
Is there anything remaining to do for this issue?
(btw, I'm glad this has been implemented, thanks!)

**Comment by rfindler** [comment]
Looks done to me! I'll close, but anyone please feel free to reopen if there's something I missed.
