### ISSUE TITLE
DrRacket Internal Error

### ISSUE THREAD

**Issue by soegaard** [racket/drracket#205]
I somehow provoked the following error:

close-status-line: status line not open 'drracket:check-syntax:status
  context...:
   /Applications/Racket v6.12/share/pkgs/gui-lib/framework/private/frame.rkt:610:7
   /Applications/Racket v6.12/share/pkgs/drracket/drracket/private/syncheck/gui.rkt:2314:14: cleanup
   /Applications/Racket v6.12/share/pkgs/drracket/drracket/private/syncheck/gui.rkt:2435:24
   /Applications/Racket v6.12/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:428:6
   /Applications/Racket v6.12/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:479:32
   /Applications/Racket v6.12/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:627:3

**Comment by soegaard** [comment]
Closing. A way to reproduce the error is missing.

**Comment by rfindler** [comment]
Thanks Jens Axel. I think there must be a race condition somehow somewhere
with that code, as I see the same thing from time to time in the test
suites.
