### ISSUE TITLE
Background expansion chokes on this program

### ISSUE THREAD

**Issue by dvanhorn** [racket/drracket#206]
The following program will cause the background expansion in DrRacket to run out of memory (or sometimes DrRacket just becomes unresponsive and has to be force-quit).  I see this behavior in 6.10.1 and 6.12.

```racket
#lang racket
(define posn/c
  (->i ([msg 'posn])
       (res (msg)
            (-> posn/c))))
```

/cc @philnguyen

**Comment by rfindler** [comment]
Thanks!
