### ISSUE TITLE
Defining functions that prefix with "def" gives incorrect syntax highlighting

### ISSUE THREAD

**Issue by Larkenx** [racket/drracket#207]
```racket
(define (definitely-not-define a b)
    (+ a b))
```

When I define a new function or variable by any means that contains the prefix `def`, DrRacket treats the newly defined function or variable as a define keyword and applies the syntax highlighting as if it were a keyword.

**Comment by rfindler** [comment]
This is an unfortunate consequence of how indentation works. Feel free to adjust your preferences to get rid of this behavior (preferences -> Editing -> Indenting -> "extra regexp")

**Comment by Larkenx** [comment]
Setting the extra regexp to `^define$` works great for me
