### ISSUE TITLE
Interactions panel "Save image..." function adds extra pixels

### ISSUE THREAD

**Issue by daniig** [racket/drracket#213]
I have no idea if this is related to Dr. Racket, htdp-lib, or something else, so apologies in advance if this is the wrong place.

If I generate an image like this:

`(define blue-rectangle (rectangle 656 500 "solid" "blue"))`

I can either save it this way:

`(save-image blue-rectangle "rectangle.png")`

which correctly generates a 656x500 PNG image, or I can display it in the interactions window by evaluating `blue-rectangle`, then right-clicking on it, and selecting the "Save image..." function.

In this last case, the generated PNG file (attached) is 657x501 pixels, i.e. it has one extra column and one extra row. Those extra pixels are fully transparent. I am currently on racket-6.12-x86_64 on Windows 8.1.

![rectangle](https://user-images.githubusercontent.com/3658894/41410215-06e6d604-6fd9-11e8-9847-47c1274bc900.png)

**Comment by mfelleisen** [comment]
Please see http://docs.racket-lang.org/teachpack/2htdpimage-guide.html?q=bitmap#%28part._nitty-gritty%29 <http://docs.racket-lang.org/teachpack/2htdpimage-guide.html?q=bitmap#(part._nitty-gritty)>

**Comment by daniig** [comment]
Thanks for pointing that out! I was not aware of that. False alarm then, I am closing the issue.
