### ISSUE TITLE
why not make the mini map tree?

### ISSUE THREAD

**Issue by ltoddy** [racket/drracket#216]
as the topic.

**Comment by soegaard** [comment]
Can you elaborate?

/Jens Axel

**Comment by ltoddy** [comment]
![image](https://user-images.githubusercontent.com/20920763/41538967-234c8276-733f-11e8-9940-4b9c084f0ea1.png)

This a the vscode.
There is a directory tree on the left.

**Comment by sorawee** [comment]
FWIW, there's a DrRacket plugin by @Syntacticlosure that does exactly this. See https://docs.racket-lang.org/files-viewer/index.html for more details.

**Comment by spdegabrielle** [comment]
@sorawee should we look at adding files-viewer to DrRacket?

**Comment by sorawee** [comment]
Let's discuss at https://github.com/racket/racket/issues/2162?

**Comment by sorawee** [comment]
And I think we can close this issue. If file viewer as a plugin suffices for @ltoddy, now you know where to look. But if you want this to be a feature of DrRacket by default, then let's discuss at the other issue.

**Comment by ltoddy** [comment]
@sorawee 
Yes, I install the `files-viewer`, but it has been a long time since maintenance.

**Comment by ltoddy** [comment]
> @sorawee
> Yes, I install the `files-viewer`, but it has been a long time since maintenance.

it's not work now, incorrect syntax in code. So, I have to download the source code to change it by myself.

**Comment by spdegabrielle** [comment]
Thank you @ltoddy :)
Have you logged the issue on the files viewer repository on github? https://github.com/MatrixForChange/files-viewer/issues/new

**Comment by ltoddy** [comment]
> Thank you @ltoddy :)
> Have you logged the issue on the files viewer repository on github? https://github.com/MatrixForChange/files-viewer/issues/new

No, I'm familiar `files-viewer` author.

**Comment by Syntacticlosure** [comment]
> > Thank you @ltoddy :)
> > Have you logged the issue on the files viewer repository on github? https://github.com/MatrixForChange/files-viewer/issues/new
> 
> No, I'm familiar `files-viewer` author.

I believe the reason is your racket version is too old.

**Comment by spdegabrielle** [comment]
Hi @ltoddy can you close this issue? - consider it a duplicate of racket/racket#2162

**Comment by ltoddy** [comment]
> Hi @ltoddy can you close this issue? - consider it a duplicate of [racket/racket#2162](https://github.com/racket/racket/issues/2162)

ok, (最近racket是怎么了, 开始大量回复issue...

**Comment by spdegabrielle** [comment]
> 最近racket是怎么了, 开始大量回复issue...
@ltoddy I just had some free time and I think you raised a good issue. 👍
