### ISSUE TITLE
function(check-expect, HtDP) have mistranslation.

### ISSUE THREAD

**Issue by black7375** [racket/drracket#218]
https://docs.racket-lang.org/htdp-langs/beginner.html
HtDP's function, check-expect, have mistranslation.

in english
![in-english](https://user-images.githubusercontent.com/25581533/41876173-ee8a9130-7907-11e8-8a92-e36c6f9dc7ba.png)

in korean
![in-korean](https://user-images.githubusercontent.com/25581533/41876112-c40be184-7907-11e8-88a4-84962b3038e7.png)

please change to `all_test_count개 중 failed_test_count개 테스트 실패함. ` 
English and Korean differ in word order.

**Comment by rfindler** [comment]
Thanks for spotting this problem. Unfortunately, I cannot figure out exactly how to make the suggested change. Maybe if you have a look at how this works, you can suggest something more specific?

In particular, please see this file:

https://github.com/racket/string-constants/blob/master/string-constants-lib/string-constants/private/korean-string-constants.rkt#L1334

The korean text that you see there is used in that spot, with the two numbers "1" and "3" put in for the two "~a"s, in that order -- at least, in this example. In general, it puts the number of failures first and the total number of tests second into that string.

Can you suggest an alternative?

Alternatively, maybe it would be better to contact `racket-korean-translation@googlegroups.com`.

Thanks!

**Comment by black7375** [comment]
It goes into the sentence in order..

I suggest this code.

```
(test-engine-m-of-n-tests-failed "~a개가 ~a개 테스트 중 실패함.")
(test-engine-m-of-n-checks-failed "~a개가 ~a개 점검 중 실패함.")
```

Now it has the right meaning.  

Thank you for reading this issue!
