### ISSUE TITLE
DrRacket should not parse whole file when just a comment is being written

### ISSUE THREAD

**Issue by kghose** [racket/drracket#22]
Currently, when a block comment is being written, with every keystroke the whole source seems to be parsed - the editor flickers. This is not needed when a comment is being written and serves as a barrier to writing long comments in a program. It would be nice if the source parsing could be made more context aware, so it does not do a lot of heavy lifting when a comment is being edited - possibly just parsing to check if the end of block comment characters have been typed. Thanks!

**Comment by rfindler** [comment]
It doesn't do that in the general case. Perhaps you can supply a more concrete (hopefully small) example that will illustrate?

For my part, here's one where it doesn't do that:

```
#lang racket
#| block comment |#
(+ 1 2)
```

Editing in the block comment doesn't cause any flicker that I see and the code is certainly not processing the portion of the editor containing the addition expression.

**Comment by kghose** [comment]
https://www.youtube.com/watch?v=rP8e7KEzLRU&feature=youtu.be

This is a screen cast of what I mean. This is related to the syntax coloring, probably.

**Comment by rfindler** [comment]
Thank you, this is clear.

**Comment by rfindler** [comment]
Okay, it appears that this problem was introduced between version 6.0 and 6.1 and it affects only editing the first token in the file.

**Comment by kghose** [comment]
Wow, thanks for tracking this down. So you didn't see this because your comment block was the second token?

**Comment by rfindler** [comment]
Right. But I haven't actually found the bug yet. :)

**Comment by rfindler** [comment]
This seems to fix it https://github.com/racket/drracket/commit/9da882986495cc3c2d9315532403134d4e00ae80

**Comment by kghose** [comment]
Cool, thanks! Is there a way to update my local DrRacket to this new
version? I think, originally, I just used the installer. I'm on a mac.

**Comment by rfindler** [comment]
You can download a snapshot build from last night: http://pre.racket-lang.org/installers/ but it is just a development snapshot. They are generally pretty reliable, but not as reliable as the official releases.
