### ISSUE TITLE
DrRacket Internal Error

### ISSUE THREAD

**Issue by soegaard** [racket/drracket#221]
How to reproduce:

Open file A.rkt and B.rkt in DrRacket in two tabs.
(File B requires file A.)
In file A make a region using, say, M-right to highlight a word.
Switch to tab A. Use Check Syntax. Then right click
on an identifier from file A and choose "Jump to Definition (in other file)".

```
send: target is not an object
  target: #<path:/Users/soegaard/Dropbox/GitHub/remacs/simple.rkt>
  method name: set-caret-owner
  context...:
   /Applications/Racket v6.12/collects/racket/private/class-internal.rkt:4610:0: obj-error35
   /Applications/Racket v6.12/share/pkgs/drracket/drracket/private/syncheck/gui.rkt:1818:12: jump-to method in ...ate/syncheck/gui.rkt:405:10
   /Applications/Racket v6.12/share/pkgs/gui-lib/mred/private/mrmenu.rkt:250:14: command method in basic-selectable-menu-item%
   /Applications/Racket v6.12/share/pkgs/gui-lib/mred/private/mrpopup.rkt:49:38: go
   /Applications/Racket v6.12/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:428:6
   /Applications/Racket v6.12/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:479:32
   /Applications/Racket v6.12/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:627:3

```

**Comment by jbclements** [comment]
I was unable to reproduce this error.

1) Tiny pedantic error: did you mean <shift-meta-right> to highlight a word? I believe that <meta-right> moves the cursor but does not highlight text.

2) In one of your steps you write “Switch to tab A”. But I was already in tab A, as a result of the previous step, no?

3) Could this be a consequence of using a Dropbox-related folder? AFAIK, the problems that this one reminds me of were related to Windows, but perhaps it might make a difference?

**Comment by rfindler** [comment]
@jbclements are you using a version newer than 6.12? I recall fixing a bug like this one not too long ago (I'm not positive it was the same, tho).

**Comment by jbclements** [comment]
Ooh, sorry, good point: 

Welcome to DrRacket, version 6.90.0.30--2018-06-06(-/f) [3m].
Language: racket, with debugging; memory limit: 1024 MB.
> 

So it is a fairly old version that I’m using, but more recent than 6.12.

John

**Comment by soegaard** [comment]
I was using 6.12 - forgot about 6.90.

Great to hear that the bug is fixed already

/Jens Axel
