### ISSUE TITLE
background expansion (?) sometimes runs out of memory when opening collects/racket/stream.rkt

### ISSUE THREAD

**Issue by gfbee** [racket/drracket#227]
This isn't a big deal, but noted in case it points to a larger issue.

Happens on Mac OS, with:
```
Welcome to DrRacket, version 7.0 [3m].
Language: Determine language from source; memory limit: 2000 MB.
```
Minimal to reproduce: start DrRacket with `#lang racket` as the default lang line, last opened without custom language settings, modify the buffer (even just typing a space), then open `collects/racket/stream.rkt` in a new tab.

**Comment by rfindler** [comment]
The bad behavior is triggered by DrRacket trying to set up the initial interactions window's content, which starts https://github.com/racket/drracket/blob/master/drracket/drracket/private/rep.rkt#L1861 and the continues into `evaluate-from-port`.

**Comment by rfindler** [comment]
Here's some code that is doing what DrRacket is doing, effectively, and it also fails to terminate. It may be that DrRacket just shouldn't be trying to do this thing, of course! The goal is to create a namespace for the initial read-eval-print loop and the two pieces that are jammed together in the code below are the setup in [`set-basic-parameters` in eval.rkt](https://github.com/racket/drracket/blob/master/drracket/drracket/private/eval.rkt#L169-L177) and the code mentioned above from rep.rkt which is trying to get a starter namespace for the repl that is like what the definitions contains but doesn't actually run the definitions window (so just tries to be in the right language).

```
#lang racket

(define path (collection-file-path "generator.rkt" "racket"))
(define resolved-modpath
  (module-path-index-resolve
   (module-path-index-join
    path
    #f)))

(define mred-spec '(lib "mred/mred.rkt"))
(dynamic-require mred-spec #f)
(define (get-name spec)
  (if (symbol? spec)
      spec
      ((current-module-name-resolver) spec #f #f #t)))
(define mred-name (get-name mred-spec))

(define orig-namespace (current-namespace))

(void
 (sync
  (thread
   (λ ()
     (current-namespace (make-base-empty-namespace))
     (read-accept-reader #t)
     (namespace-attach-module orig-namespace mred-name)
     (parameterize ([current-module-declare-name resolved-modpath]
                    [current-module-declare-source path])
       (define port (open-input-string "#lang racket\n" path))
       (port-count-lines! port)
       (define stx (read-syntax path port))
       (define module-here (datum->syntax #'here 'module #'module))
       (define module-expr
         (syntax-case stx ()
           [(module . more)
            (datum->syntax stx `(,module-here . ,#'more) stx stx)]))
       (printf "starting\n")
       (eval-syntax module-expr)
       (printf "done\n"))))))
```

**Comment by rfindler** [comment]
The code above terminates in 7.5 but not in 7.6.

**Comment by mflatt** [comment]
The main problem here is that the redeclaration of an attached module should have been disallowed, but it was only disallowed in the original namespace.

If you drop the namespace change and the attach, then redeclaration is allowed, but the declaration creates a cycle (because `racket` depends on `racket/generator`) — which is now reported with a little more detail. When the redeclaration is incorrectly allowed in a new namespace, then it still creates a cycle, but the interaction of different namespaces prevents the cycle from being detected.

**Comment by rfindler** [comment]
This seems to be fixed now.
