### ISSUE TITLE
Trackpad scrolling hardly working

### ISSUE THREAD

**Issue by jcolivo** [racket/drracket#233]
Hello, I love Dr. Racket, and I'd like to submit the following issue:

Computers: ThinkPad 25 and Surface Go with Surface Go keyboard cover
Operating System: Windows 10

The two-finger trackpad scrolling hardly works in Dr. Racket in the aforementioned computers; two-finger trackpad scrolling is unresponsive most of the time, and very choppy when it does. Mouse wheel and TrackPoint scrolling works as expected (always responsive, smooth and no choppiness).  Dragging the scroll bar using trackpad, mouse and TrackPoint also works as expected in these computers. 

I would like to point out that this issue does not occur in Mac OS - two finger scrolling via trackpad works as it should. 

Please let me know if you need clarification or help from me. 

Thank you very much for your great work!

**Comment by mflatt** [comment]
Thanks for the report! I think this problem may be fixed for the next release. You could help by checking whether at snapshot build at http://pre.racket-lang.org/ works any better and reporting back, in case we still don't have it right.

**Comment by jcolivo** [comment]
Thanks Matthew! I am grateful for your work. The trackpad scrolling in this version is light years better! Awesome work! However, if I may, comparing with other Windows apps (and the Mac version of Drracket), the scrolling in this version of Drracket (7.0.0.20--2018-10-06(e60a78aad9/a)) is still slightly choppy - not as responsive as the other apps. Nonetheless, it is very usable now. Thank you for working on this issue!

**Comment by jcolivo** [comment]
I should have tested a little longer before I replied yesterday. I noticed the hesitation (the choppiness I referred to previously) in the scrolling when I click somewhere within a function expression, and the "syntax helper" (not sure what it's named, but it's the large arrow on the top right of the editor) starts up. Moreover, I just noticed today that this happens regardless the device I am scrolling with (trackpad, track point, mouse). It's just momentary while this feature kicks o;, and once it does, scrolling operates perfectly fine.

**Comment by mflatt** [comment]
Thanks for the helpful feedback! Since the specific scrolling problem seems to be fixed, I'll close the issue.

**Comment by jcolivo** [comment]
Agreed. Thanks for your great work!

**Comment by william-reed** [comment]
having this issue in the current version
