### ISSUE TITLE
error highlighting disrupted by coverage tool

### ISSUE THREAD

**Issue by jbclements** [racket/drracket#234]
When "syntactic test suite coverage" is enabled, the wrong (i.e. too-large) section of the code can be highlighted. 

To reproduce:

1) open buffer set to "use #lang" language, enable syntactic test suite coverage
2) paste this program:
```racket
#lang racket

(define (string-oth s n)
  s)
 
(define (my-fun s)
  (string-oth (s (- 1 (string-length s))))) 

(my-fun "hello world")
```
3) run, and see whole definition of my-fun highlighted rather than just call to s.

**Comment by jbclements** [comment]
Should have added: version is 7.0.0.20--2018-09-12(-/f) [3m].

**Comment by mfelleisen** [comment]
I am having an off-line conversation with Robby and Matthew on this because of the project I am running. Let’s discuss in STL.

**Comment by jbclements** [comment]
Sounds good.
