### ISSUE TITLE
Touchpad scrolling on macOS extremely choppy

### ISSUE THREAD

**Issue by jyoo980** [racket/drracket#246]
Hi,

I understand this issue has come up before in #233, but it seems to persist after the latest updates. 

**Here's a description of the issue:**
* Unresponsive scrolling via touchpad
* Window continues scrolling long after scrolling motions have stopped on touchpad

**And here is the current setup on which this issue is happening**
* 2016 MacBook Pro
* Operating system: macOS High Sierra (version 10.13.6)
* DrRacket Version: 7.1 (latest)

**Steps to Reproduce**
* Open DrRacket (preferably with a file large enough to let you scroll)
* Use touchpad to scroll

Thanks for the work you've all done for DrRacket. My school uses it extensively, and I use it almost every day when I TA for the a course which exclusively uses DrRacket. There are over 800 students at my school alone that use this IDE, and I know all of them would be immeasurably grateful if this issue was fixed!

**Comment by JustinHuPrime** [comment]
This doesn't seem to happen on my machine. Could it be OS-specific? Touchpad scrolling is natural, but scrolling in general occasionally "sticks" - sometimes the window, when scrolled to either extreme, stutters when trying to scroll away from said extreme.

**Setup**

- Racket 7.1
- Dell Inspiron
- Ubuntu 18.10, Linux kernel 4.15.0-36-generic, x86_64

**Comment by jbclements** [comment]
FWIW, I believe this has been an issue for many years. I believe that “solving” this—that is, giving the MacOS DrRacket the same pixel-level scrolling behavior as other typical OS X applications—would require a fundamental redesign of DrRacket’s GUI layer. My personal advice to you and to all of my students is to use pgup/pgdown and other navigation methods. I would be delighted to be proven wrong!

John

**Comment by jyoo980** [comment]
@jbclements 

Hi John. Thanks for your response. Would the fact that the scrolling becomes normal when I connect to an external mouse still suggest that there is a problem with the macOS DrRacket's GUI layer? It seems to be almost hardware dependent.

**Comment by jbclements** [comment]
@jyoo980 
Whoa! news to me. I don't actually *own* an external mouse. I don't think you mentioned this earlier? That could be very good news indeed.

To be specific: when you talk about using an external mouse, are you referring to using the scroll wheel on the top of a mouse, or about using the mouse to drag the scroll bar thumb? I definitely agree that dragging the thumb is much crisper than swiping, but that doesn't surprise me.

**Comment by jyoo980** [comment]
@jbclements 

I'm currently using the scroll wheel, which mitigates the issue with the touchpad altogether. Using the cursor with the external mouse to drag the scrollbar around is also very fluid. 

I'll try to use other external mice + other external input devices to see if there's differences as well...

Thanks!

**Comment by william-reed** [comment]
Scrolling on my MacBook is absolutely miserable in Dr. Racket
This is a fundamental feature of any GUI based editor >:(

**Comment by tgbugs** [comment]
I can produce similar behavior by scrolling with a trackpoint in linux, or by manually dragging the scrollbar (!). Another program that shows similar issues is emacs (though strangely only in the upward direction), gvim running through gtk3 has no issues. This suggests to me that the issue likely has to do with how frequently trackpoints and touchpads send scroll events. One piece of evidence supporting this is that shrinking the window vertically fixes the manual scrollbar dragging lag, but does not fix the trackpoint scrolling lag.

A workaround might be to accumulate many of the small deltas that occur at a high frequency into a single larger delta that fires at a more reasonable frequency.

**Comment by greghendershott** [comment]
> Another program that shows similar issues is emacs (though strangely only in the upward direction)

That specific thing sounds to me like it could be due to Emacs using [a cache that can be used scrolling down, but not up](https://www.gnu.org/software/emacs/manual/html_node/elisp/Parsing-Expressions.html). To test that theory, you could change a buffer from `<whatever>-mode` to `fundamental-mode`, and see if scrolling up is now faster.

Not to make this even more OT, but: Emacs diffs a "shadow display" much like how React diffs a "shadow DOM". This is [both awesome and awful](https://www.facebook.com/notes/daniel-colascione/buttery-smooth-emacs/10155313440066102/). :smile:

**Comment by jackpmastrangelo** [comment]
Hey all,
I opened a related issue https://github.com/racket/racket/issues/2861 on the racket repo but it would probably go better here.

At least for me the issue seems explicitly related to having a retina display, could prove useful here.

**Comment by jackfirth** [comment]
> I believe that “solving” this—that is, giving the MacOS DrRacket the same pixel-level scrolling behavior as other typical OS X applications—would require a fundamental redesign of DrRacket’s GUI layer.

@jbclements I know it's been a while since you made this comment, but could you elaborate? What needs to be redesigned and why is it causing the scrolling issue? I ask with the faint hope that there's something I can do to help fix this issue.

**Comment by jackfirth** [comment]
Minor update: with Racket 7.4, I've noticed this problem is **much** worse with the ChezScheme variant of Racket than the normal 3m variant. DrRacket CS 7.4 is virtually unusable on macOS.

**Comment by jackfirth** [comment]
[Disabling inertial scrolling](https://www.idownloadblog.com/2017/01/17/how-to-disable-inertial-scrolling-on-your-mac/) makes this problem slightly better. With inertial scrolling, DrRacket's slow handling of scroll events is compounded by the extra scrolling events sent after letting go of the trackpad, causing DrRacket to spend several seconds after letting go just... scrolling, completely uninterruptibly. Disabling inertial scroll at least makes the extra scrolling go away, but it doesn't do anything to make scrolling itself happen faster.

**Comment by k4rtik** [comment]
With release of v7.6, this looks fixed now? https://blog.racket-lang.org/2020/02/racket-v7-6.html and https://github.com/racket/drracket/commit/fc6c09624f2e3924e9d8215531f0e4ec2b4f712f

On my iMac, I notice a better scroll experience. I am on  v7.6 [cs].

**Comment by jackfirth** [comment]
I'm on 7.6 (regular though, not CS) and it looks completely fixed to me too.

**Comment by jbclements** [comment]
Sounds like we can maybe close this issue. Fantastic!
