### ISSUE TITLE
Pasted ligatures normalized only in first line of paste

### ISSUE THREAD

**Issue by jbclements** [racket/drracket#252]
In OS X, DrRacket (version 7.1.0.8--2018-12-01(-/f) [3m]) Pasting a multi-line block of text with ligatures in more than one line appears to normalize the ligatures only in the first line in which they appear.

To reproduce:

1) Open a new DrRacket tab
2) Copy this four-line block of text:
x² x²
x² x²
x² x²
x² x²
3) Paste it in DrRacket. See dialog about whether to normalize ligatures, click "Normalize".
4) See that the first line gets changed to x2 x2, but the others are left alone.

**Comment by OxSon** [comment]
This appears to no longer be the case.

**Comment by rfindler** [comment]
Looks like this commit fixed it and I put the wrong message, not realizing the issue was in another repo.

https://github.com/racket/gui/commit/774a6b886bf60c7de7fc847ff9c80310c148b89d
