### ISSUE TITLE
"Scribble PDF" button on windows is missing

### ISSUE THREAD

**Issue by laszlokorte** [racket/drracket#254]
On MacOS when editing a `#lang scribble/base` DrRacket shows a button "Scribble PDF" to generate a PDF and open it in preview:

![scribble-pdf-button](https://user-images.githubusercontent.com/26493/50692865-94f66e80-1035-11e9-9127-dcbf86435931.png)

On Windows this button is missing, as already reported here:
https://lists.racket-lang.org/users/archive/2015-March/066280.html

Indeed there is a operating system check to only show the button on MacOS:
https://github.com/racket/drracket/blob/master/drracket/scribble/tools/drracket-buttons.rkt#L70-L79

And opening the generated PDF is done via the `open` shell command which apparently on works on Mac:
https://github.com/racket/drracket/blob/master/drracket/scribble/tools/drracket-buttons.rkt#L63-L64

On the other hand HTML files can be generated and opened by DrRacket across all platforms and are presented to the user via `send-url/file`.

### Proposed Solution

I tried `send-url/file` for PDF files and it works on both Windows and Mac. On Windows it opens the file in the PDF viewer that is configured as default in the system preferences. On Mac it shows the PDF in the default web browser (all of them can render PDFs nowadays).

So I propose the replace the `open` shell command with `send-url/file` and enable the "Scribble PDF" button across all platforms.

I did not tried `send-url/file` on linux but even if it does not work on linux the "Scribble PDF" button should be made available on Windows. Currently I am teaching Racket and many students are running Windows.

**Comment by rfindler** [comment]
I would prefer not to make that change for mac os, but it sounds reasonable for windows. (I don't mind if you want to add a preference.)

**Comment by laszlokorte** [comment]
Leaving MacOS as is and just making the change for windows would also be great!

**Comment by laszlokorte** [comment]
I would create a pull request but I don't know how to build/test DrRacket.

**Comment by rfindler** [comment]
I don't seem to have a windows installation with latex on it. Do you? If so, when you run this program, do you get a good pdf out?

```
#lang racket/base
(require scribble/private/run-pdflatex)
(call-with-output-file "tmp.tex"
  (λ (port)
    (fprintf port "\\documentclass{article}\n\\begin{document}\nhi\\end{document}\n"))
  #:exists 'truncate)
(void (run-pdflatex "tmp.tex"))
```

**Comment by laszlokorte** [comment]
Yes that works. As you can see in my pull request I tested the "Scribble PDF" button on macos, linux and windows and it works on all 3 platforms including the latex->pdf conversion.

![bildschirmfoto 2019-01-08 um 21 20 03](https://user-images.githubusercontent.com/26493/50856521-3b6ea680-138b-11e9-810c-450feb0111f7.png)

**Comment by rfindler** [comment]
Ah, sorry about that. I somehow missed your pull request. Thank you for taking the time to make it!

**Comment by sjmackenzie** [comment]
On linux, (nixos):
```
scribble: loading xref
scribble: rendering
/bin/sh: open: command not found
```

**Comment by rfindler** [comment]
On linux, DrRacket assumes there is an `open` command to use to show the pdf. Is there a different command it should be using sometimes?

**Comment by rmculpepper** [comment]
Probably `xdg-open`.

**Comment by sjmackenzie** [comment]
I believe `xdg-open` is what the cool kids use. https://linux.die.net/man/1/xdg-open
