### ISSUE TITLE
The increase/decrease font menu items don't show up in Unity

### ISSUE THREAD

**Issue by takikawa** [racket/drracket#27]
Screenshot:

![http://i.imgur.com/1urJn0b.png](http://i.imgur.com/1urJn0b.png)

Note the missing menu items at the top. This is on Ubuntu 15.10 with a mostly default setup with Racket v6.3.

**Comment by rfindler** [comment]
I think this has been reported elsewhere already (but I forget where; it
was recently) and also this is a racket/gui repo issue, not a
racket/drracket issue.

I don't have a way to test this out easily (my ubuntu vm bitrotted away,
sorry) but what is probably happening is a well-known problem where "too
much" work is happening in the on-demand callback. DrRacket is certainly
doing something like this:

```
#lang racket/gui
(define f (new frame% [label ""]))
(define mb (new menu-bar% [parent f]))
(define m (new menu% [label "File"] [parent mb]))
(define mi (new menu-item%
                [parent m]
                [label ""]
                [callback void]
                [demand-callback
                 (λ (mi)
                   (send mi set-label (format "Set Font Size to ~a" (random
100))))]))
(send f show #t)
```

where the call to `random` is replaced by something more interesting
(involving looking at preferences and whatnot). Does repeatedly opening the
menu item change the value and do you see "Set Font Size ..." in the menu
item?

**Comment by takikawa** [comment]
I'm not sure the callback is ever called. I don't see the menu item label after opening the menu (or clicking on the item). If I put in a print or error in the callback, I don't see those trigger either.

**Comment by rfindler** [comment]
This seems to work on racket version 7.9.0.14 under ubuntu 18.04. I'll close the issue but if you're still seeing problems, please do reopen it.
