### ISSUE TITLE
Erro when printing vector with print-vector-length enabled

### ISSUE THREAD

**Issue by gus-massa** [racket/drracket#275]
In DrRacket, when the output is configured as "print", the output of this program:

    #lang racket

    (struct b (x y z) #:transparent)

    (parameterize([print-vector-length #t])
      (print (vector (b 1 2 2) 3 3 3 3 3 3))) 

is  `(vector (b 1 2 2) 3)` (only one `3`).

The program is fine in plain racket, so my guess is that it is an error in the print handler that is installed by DrRacket, but I can't find where it is defined.

**Comment by rfindler** [comment]
This appears to be behavior that DrRacket inherits from `pretty-print`. Not sure if DrRacket is calling it wrong or if it shouldn't do that tho?

```
#lang racket

(parameterize([print-vector-length #t])
  (pretty-print (vector (b 1 2 2) 3 3 3 3 3 3)))
```

produces

```
(vector (b 1 2 2) 3)
```

**Comment by gus-massa** [comment]
I'll take a look at `pretty-print`, and if necessary reopen the bug there.

**Comment by samth** [comment]
@gus-massa notes that you can move this issue to the appropriate repository if you want -- see the "Transfer Issue (Beta)" link on the right side. 

![Screenshot from 2019-05-28 10-39-22](https://user-images.githubusercontent.com/244723/58487014-e8786e80-8134-11e9-8a13-b547fb99d063.png)

**Comment by gus-massa** [comment]
I don't have the "transfer issue" link. Perhaps it's rolled out only to some users because it is in beta, or perhaps I don't have enough permissions in this repository.

I have no problem if you want to transfer this to [racket/racket](https://github.com/racket/racket), in case someone want to take a look and fix it. I was just more optimistic that I can find the error there. 

---

I have a rough idea where the problem is [racket/pretty.rkt#L879](https://github.com/racket/racket/blob/master/racket/collects/racket/pretty.rkt#L879) and [racket/pretty.rkt#L1109](https://github.com/racket/racket/blob/master/racket/collects/racket/pretty.rkt#L1109), but I have to think a little how to fix it and look at the details (the details always take more time than expected (why it is called in two locations?)), so I'd probably not attempt to fix it this week. 

There is a similar problem in [racket/io/print/main.rkt#L239](https://github.com/racket/racket/blob/master/racket/src/io/print/main.rkt#L239)

**Comment by samth** [comment]
Ah, annoying that it isn't enabled for you -- apparently it requires "admin" permissions on both repositories.

**Comment by gus-massa** [comment]
Fixed in https://github.com/racket/racket/commit/964e998d704ee9f6ed5cf90bb72fb0ee6347d852
