### ISSUE TITLE
`(require (submod ···))` on the REPL has changed behavior since v6.4 

### ISSUE THREAD

**Issue by mbutterick** [racket/drracket#276]
I don’t know when this stopped working, because I don’t have every DrRacket version handy. But in v6.4, this code in the definitions window:

```racket
#lang racket
(module foo racket
  (provide x)
  (define x 42))
```

Followed by this interaction:
```
> (require (submod "." foo))
```

Made the bindings from `foo` available on the REPL, as one would hope.

But in DrRacket v7.1, the same definitions + interaction produces this error:

```
standard-module-name-resolver: no base path for relative 
submodule path: (submod "." foo)
```

**Comment by rfindler** [comment]
This worked in 6.12 and not in 7.0.
