### ISSUE TITLE
update Drracket documentation to add section and screenshots of "signature boxes"

### ISSUE THREAD

**Issue by spdegabrielle** [racket/drracket#291]
ref #172 @rfindler 
update Drracket documentation to add section and screenshots of "signature boxes"

**Comment by spdegabrielle** [comment]
Thank you @rfindler

**Comment by jackfirth** [comment]
There's also the `scribble/bluebox` library, could we use the term "signature box" there too? We could rename the module `scribble/signature-box` and change the function names. While still preserving the current module and function names as deprecated aliases, of course.

**Comment by spdegabrielle** [comment]
@jackfirth yes . Please raise a new issue and reference this one for context.

**Comment by jackfirth** [comment]
@spdegabrielle Done!
