### ISSUE TITLE
please create a issue label 'good first issue' and 'help wanted' for this repo

### ISSUE THREAD

**Issue by spdegabrielle** [racket/drracket#298]
_"To attract new contributors, issues with labels that start with `good first issue` or `help wanted` are featured on the user dashboard, search, and topic pages"_ - [Helping new contributors find your project with labels](https://help.github.com/en/articles/helping-new-contributors-find-your-project-with-labels)

Both the /racket and /typed-racket have these labels available.

FYI 
- https://racket.slack.com/archives/C09L257PY/p1565255893113200
- https://www.reddit.com/r/Racket/comments/cnjcwq/learning_contributing

**Comment by spdegabrielle** [comment]
https://racket.slack.com/archives/C09L257PY/p1565255893113200
https://www.reddit.com/r/Racket/comments/cnjcwq/learning_contributing

**Comment by spdegabrielle** [comment]
https://help.github.com/en/articles/helping-new-contributors-find-your-project-with-labels

**Comment by bennn** [comment]
I added "good-first-issue".
