### ISSUE TITLE
Incorrect index when searching in DrRacket

### ISSUE THREAD

**Issue by guojing0** [racket/drracket#304]
When I search for “module” from [this program](https://my.eng.utah.edu/~cs3520/function2.rkt), the search bar at the end of DrRacket displays that there are 5 “module”s in the text, which is correct.

However, when first “module” is highlighted, search bar displays “0/5 match;” when the last “module” is highlighted, it displays “4/5 match.” If I click “Next,” the first “module” is again highlighted and “4/5” changes to “0/5.”

My DrRacket version is 7.4

**Comment by jbclements** [comment]
Yes, I believe that's the expected behavior. Okay if I close this?

**Comment by guojing0** [comment]
Yes.

**Comment by mflatt** [comment]
Although I'm a fan of 0-based indexing, I'm surprised that counting from "0/5" to "4/5" is the expected behavior. Usually the "/" notation for "out of" goes with 1-based counting. Am I missing something?

**Comment by rfindler** [comment]
Are you using the latest version of DrRacket?  I see 1/5 in my version of DrRacket (as attached).

![Screen Shot 2019-08-30 at 5 17 02 PM](https://user-images.githubusercontent.com/399024/64053906-2200b180-cb4a-11e9-9dd9-5407d34ef6e9.png)

**Comment by guojing0** [comment]
Yes, I use the latest stable version.

![Snip20190830_1](https://user-images.githubusercontent.com/3425792/64053980-2a54ee80-cb42-11e9-9190-1fb2071fb050.png)
![Snip20190830_2](https://user-images.githubusercontent.com/3425792/64053981-2a54ee80-cb42-11e9-813f-904ad07649f7.png)

**Comment by mflatt** [comment]
I see counting from "0/5" when I have "replace" visible, but I see counting from "1/5" when I hide "replace" and step to the next match.

**Comment by rfindler** [comment]
Ah, thanks!
