### ISSUE TITLE
Startup on ada lovelaces birthday takes about 2x longer

### ISSUE THREAD

**Issue by florence** [racket/drracket#32]
On not ada lovelaces birthday startup took 8811 ms. With drracket convinced it was her birthday it took 21601 ms. (With sample size N=1)

**Comment by samth** [comment]
Yeah, some people on IRC reported this too. But then I tried to measure and couldn't, so well done.

My guess is that it's the sliding-window pict computation here: https://github.com/racket/drracket/blob/master/drracket/drracket/private/ada.rkt#L130

**Comment by rfindler** [comment]
The measurement technique is to put a

```
(collect-garbage)
(printf "~s\n" (current-process-milliseconds))
```

just after the call `(close-splash)` in the drracket startup code.
