### ISSUE TITLE
Zoom out works on Mac OS, but zoom in doesn't!

### ISSUE THREAD

**Issue by seisvelas** [racket/drracket#320]
I pressed CMD - a few times to zoom out and was able to. However, now when I try to press CMD + to zoom back in nothing happens (well, it enters the + character in the editor). Unless the command keys to zoom in are different, looks like possible bug!

**Comment by jackfirth** [comment]
What versions of macOS and DrRacket are you seeing this problem in? I'm able to zoom in and out on macOS Mojave (10.14.6) with DrRacket 7.3.

**Comment by rfindler** [comment]
Also, what kind of keyboard do you have (i.e. is a US keyboard or some other kind of keyboard)? And how do you type the - character?
