### ISSUE TITLE
Forcing square bracket doesn't interact well with automatic parentheses

### ISSUE THREAD

**Issue by sorawee** [racket/drracket#329]
When "Enable automatic parentheses, square brackets, and quotes" is checked, we get a nice feature where we can select a text, press `(` or `[`, and get parenthesized/bracketized term.

When "Automatically adjust opening square brackets" is checked, we get a nice feature where `[` magically switch to either `(` or `[` automatically. Within this feature, we can force typing character `[` by using `ctrl-[`.

It turns out that `ctrl-[` doesn't interact well with the first feature. That is: suppose I have a text `abc`.

- Select "abc"
- Hit `ctrl-[`

Then instead of replacing the text with `[abc]`, it replaces with `[]`.

**Comment by jbclements** [comment]
I think you're looking for "escape-[". Specifically, when I look at my keybindings, i see that 

"esc;["  is bound to "insert-[]-pair"
and that
"c:[" is bound to "non-clever-open-square-bracket"

So in fact, I think that the control-bracket binding is specifically designed to defeat the behavior that you're looking for, and I think you can get what you want either by using escape-bracket, or by adjusting your keybindings to bind "c:[" to "insert-[]-pair".

**Comment by sorawee** [comment]
Nice, and with "Treat alt key as meta" I can use `alt-[` instead. Thanks!
