### ISSUE TITLE
Can not input Chinese by Microsoft Pinyin in windows10 1909

### ISSUE THREAD

**Issue by TLIFC** [racket/drracket#331]
In DrRacket 7.5 I can not input Chinese by Microsoft Pinyin in windows 10 1909.
And I can not open https://bugs.racket-lang.org/, in DrRacket I can not submit this problem.

**Comment by mflatt** [comment]
This should be fixed for the next release. You can try a pre-release build from here:

  https://snapshot.racket-lang.org/
