### ISSUE TITLE
overly finicky behavior in the presence of unsaved files [mac os / 7.5]

### ISSUE THREAD

**Issue by mbutterick** [racket/drracket#333]
1. Create and save a file `"foo.rkt"`

2. In another tab, create and save a second file `"bar.rkt"`

3. Change `"foo.rkt"` but don’t save.

4. Attempt to run `"bar.rkt"`. You will get the error shown below about “The file “foo.rkt” is not saved”. Why should DrRacket care whether other files are saved?

5. You can open other tabs or windows with new files. Every time you try to run one of these, DrRacket will still complain about `"foo.rkt"` not being saved.

PS. The text in the warning dialog is cut off. The complete message is “The file “foo.rkt” is not saved; save it before Run?”

![Screen Shot 2019-12-30 at Dec 30  1 27 58 PM](https://user-images.githubusercontent.com/1425051/71601424-3492f380-2b08-11ea-8a07-55a44ea536f9.gif)

**Comment by rfindler** [comment]
The goal is to improve the experience for people who open multiple files in the same program and edit them, forget to save, click Run and get confused when the program still has the same behavior.

Many apps on the mac these days seem to be doing away with the save button entirely and there really isn't intended to be any difference between the view of the file in the editor window and on the file system. That seemed like too big of a step so I tried this step.

Maybe the dialog should have a "Yes, I know it isn't saved; stop bothering me about it, I prefer it to not be saved" option? Or maybe you have another suggestion that matches the above thoughts?

**Comment by mbutterick** [comment]
This seems like it should be in Preferences → General as a stronger form of "Auto-save files", for instance "Auto-save all files before Run". (Or maybe convert  “Auto-save” to a radio-button choice like “Printing Mode”.)

Short of that, a “don’t ask again, I live dangerously” option seems right.

**Comment by jackfirth** [comment]
Could DrRacket simply notice when one unsaved file is trying to require another unsaved file and override the module importing mechanism to make the first file import the unsaved in-memory version of the code, instead of the on-disk file?

**Comment by rfindler** [comment]
@mbutterick re burying the preference: that wouldn't help with the original problem this behavior is trying to protect unless it were on by default and I guess you'd find that more, not less, annoying (or else you'd have clicked that checkbox and moved on with your life already)?

@jackfirth that would be nice, I think. I prefer the idea that drracket's and the file system's view of the files are always identical (kind of doing away with the concept of an "unsaved file" all together), but I'm not sure how much pain would be involved in carrying through my preference all the way....

**Comment by jackfirth** [comment]
> I prefer the idea that drracket's and the file system's view of the files are always identical

That would be my first choice as well.

**Comment by mbutterick** [comment]
> burying the preference: that wouldn't help with the original problem this behavior is trying to protect unless it were on by default and I guess you'd find that more, not less, annoying 

Well, no more annoying than other DrRacket default behavior I disable in the preferences — one and done. Also, it seems like a pref setting would also make the new behavior less annoying for people who want it (because it would eliminate the new dialog box entirely). Everybody wins?

>  I prefer the idea that drracket's and the file system's view of the files are always identical

I concede I’m unaware of the trend toward “doing away with the save button entirely” (all my Mac apps still have it — example otherwise?) But even then, consider that DrRacket is also useful as an editor for code being run via command-line `racket` (which seems like a worthwhile compatability to preserve). If so, there’s no way to ensure this guarantee of DrRacket/filesystem synchrony without saving DrRacket files after every keystroke, which would make typing laggy and annoying, so this dream must necessarily remain incomplete.

**Comment by jackfirth** [comment]
> I concede I’m unaware of the trend toward “doing away with the save button entirely” (all my Mac apps still have it — example otherwise?)

The Atom editor has an autosave-on-change feature installed (but not enabled) by default. It simply saves your changes whenever the changed file loses focus. So it would avoid the issue DrRacket is warning about here, where one tab has code that depends on a file that's open and edited in another tab. This would also work when opening the terminal to run `racket` commands, since that would cause the edited code to lose focus.

The bigger problem I have though is when a file is open in DrRacket and I haven't changed it, but the file on disk changed. Usually this happens because I did something with Git, like check out a different branch or pull some commits. Currently I have to close and reopen anything in DrRacket that changed on disk, even if I didn't actually do anything to the file since it was last saved.

**Comment by rfindler** [comment]
> > burying the preference: that wouldn't help with the original problem this behavior is trying to protect unless it were on by default and I guess you'd find that more, not less, annoying
> 
> Well, no more annoying than other DrRacket default behavior I disable in the preferences — one and done. Also, it seems like a pref setting would also make the new behavior less annoying for people who want it (because it would eliminate the new dialog box entirely). Everybody wins?

The people who want it have this option already actually; it is the people who don't that are currently disadvantaged.

> > I prefer the idea that drracket's and the file system's view of the files are always identical
> 
> I concede I’m unaware of the trend toward “doing away with the save button entirely” (all my Mac apps still have it — example otherwise?) But even then, consider that DrRacket is also useful as an editor for code being run via command-line `racket` (which seems like worthwhile compatibility to preserve). If so, there’s no way to ensure this guarantee of DrRacket/filesystem synchrony without saving DrRacket files after every keystroke, which would make typing laggy and annoying, so this dream must necessarily remain incomplete.

I was talking about this:

https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/auto-save/

I don't think that it would make typing laggy and annoying.

**Comment by rfindler** [comment]
> > I concede I’m unaware of the trend toward “doing away with the save button entirely” (all my Mac apps still have it — example otherwise?)
> 
> The Atom editor has an autosave-on-change feature installed (but not enabled) by default. It simply saves your changes whenever the edited file loses focus. So it would avoid the issue DrRacket is warning about here, where one tab has code that depends on a file that's open and edited in another tab. This would also work when opening the terminal to run `racket` commands, since that would cause the edited code to lose focus.
> 
> The bigger problem I have though is when a file is open in DrRacket and I haven't changed it, but the file on disk changes for some external reason. Usually this happens because I did something with Git, like checking out a different branch or pulling some commits. Currently I have to close and reopen anything in DrRacket that changed on disk, even if I didn't actually do anything to the file since it was last saved.

Yeah, that problem would go away too. (Currently DrRacket has a similarly-incomplete hack for that situation; it checks the current file when you hit "Run", but that's not as good as it could be.)

**Comment by mbutterick** [comment]
> The people who want it have this option already actually

OK, so the answer is to join Team Autosave. Fair enough.

> I don't think that it would make typing laggy and annoying.

Do you what you like, though such a system seems easy to terrorize. For instance, open a multi-megabyte file in DrRacket. Select all and delete. Now hit undo & redo repeatedly. To say nothing of the latency risks introduced by networked drives, background file operations, etc.

**Comment by soegaard** [comment]
Den tir. 31. dec. 2019 kl. 00.46 skrev Matthew Butterick <
notifications@github.com>:

> I concede I’m unaware of the trend toward “doing away with the save button
> entirely” (all my Mac apps still have it — example otherwise?) But even
> then, consider that DrRacket is also useful as an editor for code being run
> via command-line racket (which seems like a worthwhile compatability to
> preserve). If so, there’s no way to ensure this guarantee of
> DrRacket/filesystem synchrony without saving DrRacket files after every
> keystroke, which would make typing laggy and annoying, so this dream must
> necessarily remain incomplete.
>
> Check this section:

https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/auto-save/


They describe both "Auto Save" and "manually save" so even if a program has
a save button,
it's possible that it auto saves too. I believe all Apple's programs do.

/Jens Axel

**Comment by rfindler** [comment]
I've added the preference, @mbutterick . https://github.com/racket/drracket/commit/95a254292ad1b43f8e474748a30e82ea2cc3086b
