### ISSUE TITLE
DrRacket bug report tools fails to submit

### ISSUE THREAD

**Issue by jamie255** [racket/drracket#340]
Just tried submitting a Bug Report using the Help -> Submit Bug Report tool in DrRacket and it failed with the following message:

Submitting bug report...

ERROR:
tcp-connect: connection failed
address: bugs.racket-lang.org
port number: 80
system error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.; errid=10060

Not sure if the tool is no longer supported or if it's a server issue

**Comment by jcolivo** [comment]
I created a new issue before finding out this was the same issue. Sorry.
[https://github.com/racket/drracket/issues/354#issue-580325690](url)

**Comment by jcolivo** [comment]
In the latest build of the 2.7 pre-release (20200420-876aff8), the `Submit Bug Report...` menu item has been removed by the developers, and replaced with `Having an Issue?...` that takes you to either the mailing list or GitHub. Very nice. 

Thanks for your work!
