### ISSUE TITLE
Repeated ESC-p (for REPL previous entry) doesn't work

### ISSUE THREAD

**Issue by sorawee** [racket/drracket#341]
Steps to reproduce:

1. Evaluate a couple of expressions in the REPL. Say, `1`, `2`, `3`, `4`.
2. Hold `ESC`. Press `p` repeatedly. 

Expected result:

The REPL switch to `4`, `3`, `2`, and then `1`.

Actual result:

The REPL switch to `4`, and then add characters `p` 3 times.

Note: a workaround is to lift `ESC` for each key combination entering.

**Comment by rfindler** [comment]
I'm not really sure we can (or should?) change this one. There are other keybindings that are more normal, tho. On the mac, the control key with the up/down arrows goes through the history (but you may have to turn off the os-level keybinding so they get passed to drracket)

**Comment by mflatt** [comment]
I don't think this can change. The ESC key is not a modifier like Shift or Control, and the underlying event mechanism doesn't report ESC like modifier keys. Note also that the key combination is reported by DrRacket as "esc;p" instead of "esc:p".

**Comment by sorawee** [comment]
Thanks. Closing then.
