### ISSUE TITLE
certain keys don't work in open & save dialogs

### ISSUE THREAD

**Issue by mbutterick** [racket/drracket#344]
DrRacket 7.5.0.14. When I save a file, the arrow keys don’t work inside the filename box. Nor do the cut/copy/paste key shortcuts. But I can use the mouse to select text, or the backspace key to delete the selected text. (And obviously use the other keys to type a filename).

![Screen Shot 2020-02-09 at Feb 09  10 13 32 AM](https://user-images.githubusercontent.com/1425051/74107435-d9034f00-4b24-11ea-898e-35af6d34a3a4.gif)

**Comment by mbutterick** [comment]
Also appears to be true that in the “open file” dialog, one cannot navigate a file list with the arrow keys

**Comment by sorawee** [comment]
Yep, I just got hit by this bug, too.

**Comment by mbutterick** [comment]
In DrR 7.6.0.12 cs, the arrow keys work in the open/save boxes, but the cut/copy/paste key shortcuts do not (though maybe they never did)

**Comment by jbclements** [comment]
What OS is this?

**Comment by sorawee** [comment]
macOS (Catalina). Looking from the screenshot, that's what @mbutterick has too.

**Comment by jbclements** [comment]
In that case, I think this is a duplicate and/or extension of 

https://github.com/racket/gui/issues/155

No?

**Comment by mbutterick** [comment]
Yes, I agree. Closing as duplicate.
