### ISSUE TITLE
Arrow keys don't move the cursor as expected

### ISSUE THREAD

**Issue by sorawee** [racket/drracket#345]
Consider

```
#lang racket

1 2 3
4 5 6
```

Position the cursor after `2`. Press either right or left arrow, then press down.

Expected: the cursor is before `6` if right arrow was chosen, or the cursor is before `5` if left arrow was chosen.
Actual: the cursor is after `5` if the right arrow was chosen, or the cursor is after `4` if left arrow was chosen.

The same issue happens after entering right or left arrow, and then up.

The issue seems to be related to the single-character token that the cursor will move into. There's no problem when moving from `a b c` to `ddddd`, but this is not true for the other direction.

```
a b c
ddddd
```

**Comment by jackfirth** [comment]
This drives me up a wall constantly, because of code like this:

```racket
(require foo
         bar
         baz)
```

If the cursor is just before `bar`, and you press the up arrow, the cursor moves left one space to be just after `require`, instead of just before `foo`.

**Comment by jbclements** [comment]
Yes, can confirm, I've been meaning to write this as an issue forever, many thanks.

**Comment by rfindler** [comment]
It appears to be a bug that's not in `text%` but is in `racket:text%`. 

```
#lang racket/gui
(require framework)

(define t (new racket:text%))
(send t insert "1 2 3\n4 5 6")
(define f (new frame% [label ""] [width 400] [height 400]))
(define ec (new editor-canvas% [parent f] [editor t]))
(send f show #t)
```

**Comment by rfindler** [comment]
Here's a version that narrows down the entry point into the problematic code:

```
#lang racket/base
(require framework racket/class racket/gui/base)

(define t (new racket:text%))
(send t insert "1 2 3\n4 5 6")
(send t set-position 3 3)
(define f (new frame% [label ""] [width 400] [height 400]))
(define ec (new editor-canvas% [parent f] [editor t]))
(send t freeze-colorer)
(send t move-position 'down)
(send t get-start-position) ;; should be 9
```

**Comment by rfindler** [comment]
Here's a version that eliminates more code (unfortunately, not the colorer; don't know what role it is playing yet).

```
#lang racket/base
(require framework racket/class racket/gui/base)

(define t (new racket:text%))
(send t insert "1 2 3\n4 5 6")
(send t set-position 3 3)
(define f (new frame% [label ""] [width 400] [height 400]))
(define ec (new editor-canvas% [parent f] [editor t]))
(send t freeze-colorer)

(define x-coordinate
  (let ([b (box 0.0)])
    (send t position-location 3 b #f #t #f #t)
    (unbox b)))

(send t find-position-in-line 1 x-coordinate #f)
```

That last result is `8` but it should be `9` (and it is if we remove the `freeze-colorer` line and replace `racket:text%` with `text%`).

**Comment by rfindler** [comment]
And here's a version that eliminates the colorer and the framework. If there aren't lots of styles, we get the right answer, but if there are, we don't (i.e. remove the `for` loop to see the right answer come out).

```
#lang racket/base
(require racket/class racket/gui/base)

(define sl (new style-list%))
(void (send sl new-named-style "style1" (send sl find-named-style "Basic")))
(void (send sl new-named-style "style2" (send sl find-named-style "Basic")))

(define t (new text%))
(define f (new frame% [label ""] [width 400] [height 400]))
(define ec (new editor-canvas% [parent f] [editor t]))

(send t set-style-list sl)
(send t insert "1 2 3\n4 5 6")
(send t set-position 3 3)

(for ([i (in-range 11)])
  (send t change-style 
        (send sl find-named-style (if (even? i) "style1" "style"))
        i (+ i 1)))

(define x-coordinate
  (let ([b (box 0.0)])
    (send t position-location 3 b #f #t #f #t)
    (unbox b)))

(printf "should be 9: ~s\n" (send t find-position-in-line 1 x-coordinate #f))
```
