### ISSUE TITLE
Text for syntax objects do not increase in size.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/drracket#35]
When I do C-+ and C-- My text size increases and decreases as I would expect. However, the text associated with syntax objects does not increase or decrease as well. This leads to oddly sized syntax objects. (That I have to use my screen magnifier to see.)

![screen shot 2016-01-28 at 4 35 19 pm](https://cloud.githubusercontent.com/assets/285926/12659541/4eb036fe-c5dd-11e5-90c9-d76d20b7955d.png)

**Comment by rfindler** [comment]
Fixed by https://github.com/racket/gui/commit/55e34bd6d4f9934beb852cfedb66cdc2e7e31dcc

**Comment by LeifAndersen** [comment]
Thanks. Except now if I have a syntax object which is inside the syntax-property of another syntax object, it becomes small again.
<img width="1280" alt="screen shot 2016-02-01 at 10 34 39 pm" src="https://cloud.githubusercontent.com/assets/285926/12739076/0f1c7354-c934-11e5-8a06-6ee0382543c2.png">

**Comment by LeifAndersen** [comment]
(For reference, you see this when you expand a module.)

**Comment by rfindler** [comment]
fixed better https://github.com/racket/gui/commit/021f9a6a0aa8ead06c20192439024ffb430f8015

**Comment by LeifAndersen** [comment]
Thanks. :)
