### ISSUE TITLE
internal error on click of bug location button... easy fix?

### ISSUE THREAD

**Issue by jbclements** [racket/drracket#358]
I don't think I'll be able to reproduce this, but the error message is really detailed, it might be an easy fix.

I clicked on the "red X" icon that takes you to the location of a bug (known in this case to be in a file open in a different editor), and got an internal error with this message:

send: no such method
  method name: get-edition
  class name: add-on-paint-logging
  context...:
   /Users/clements/racket/racket/collects/racket/private/class-internal.rkt:4679:0: obj-error
   /Users/clements/racket/racket/share/pkgs/drracket/drracket/private/stack-checkpoint.rkt:225:0: viewable-stack-out-of-date-editor?
   /Users/clements/racket/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /Users/clements/racket/racket/share/pkgs/drracket/drracket/private/debug.rkt:1078:2: open-and-highlight-in-file
   /Users/clements/racket/racket/share/pkgs/drracket/drracket/private/debug.rkt:125:6: on-event method in clickable-snip-mixin205
   /Users/clements/gui/gui-lib/mred/private/wxme/editor-canvas.rkt:412:2: on-event method in editor-canvas%
   /Users/clements/racket/racket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /Users/clements/racket/racket/collects/racket/private/more-scheme.rkt:265:2: call-with-exception-handler
   /Users/clements/gui/gui-lib/mred/private/wx/cocoa/window.rkt:897:4: dispatch-on-event method in window%
   /Users/clements/gui/gui-lib/mred/private/wx/common/queue.rkt:435:6
   /Users/clements/gui/gui-lib/mred/private/wx/common/queue.rkt:486:32
   /Users/clements/gui/gui-lib/mred/private/wx/common/queue.rkt:634:3

**Comment by rfindler** [comment]
Maybe you're not on git head?

**Comment by jbclements** [comment]
Could easily be. I’m on git head as of 2020-02-24. Feel free to close this if you’ve fixed a related defect between then & now.

John

**Comment by rfindler** [comment]
Probably fixed by https://github.com/racket/drracket/commit/582e52fce04a
