### ISSUE TITLE
Extend Lambda like keywords regex to include all forms of with-

### ISSUE THREAD

**Issue by LeifAndersen** [racket/drracket#37]
At the moment, the lambda like keyword section of the indentation preferences has a list of several `with-` statements.

However, I often see DSLs that use new `with-` forms. And while racket-mode in emacs indents these correctly, DrRacket doesn't until someone adds it to the Extra Regexp form.

Would it make sense to change the default extra regexp form to be:

```
^(for\*?(/|d$)|with-)
```

?

Thank you.

**Comment by rfindler** [comment]
Yes, I think that's a good idea.

It would probably also be good to do some checking to see if the current
setting is the old default and then set it to the new default.

**Comment by LeifAndersen** [comment]
> It would probably also be good to do some checking to see if the current setting is the old default and then set it to the new default.

Oh, does it automatically configure the regex rather than just having a default if no one has typed one in?

**Comment by rfindler** [comment]
That's what I should have done (to have the actually preference stored by
either #f or a regexp where #f means "use the default one"). But the
preference is stored only as the default. Perhaps that's also a good idea
to fix at the same time!​

**Comment by LeifAndersen** [comment]
Okay cool. Can you tell me what file deals with that preference?

**Comment by rfindler** [comment]
You want the `'framework:tabify` preference. The default is set in `framework/private/main` and probably best to use grep to figure out where it gets set/used as I'll probably miss a place if I just tell you.

**Comment by rfindler** [comment]
(it should be set only in the framework collection files)

**Comment by LeifAndersen** [comment]
That works for me. Thanks.

(I was just having trouble finding it because of all of the escapes needed in searching for that string.)

**Comment by LeifAndersen** [comment]
So, there is one problem with automatically changing it if it's not the default. Namely, if they put that regex there explicitly, it will now change without warning.

**Comment by rfindler** [comment]
Probably the right thing is to have a checkbox in the GUI that controls the editability of the text field. In other words, make the type (or/c #f regexp?) explicit in the GUI.

**Comment by LeifAndersen** [comment]
Sure, but that doesn't really change that a lot of people already have a default that they didn't intentionally make.

(Also, it seems reasonable to me to have the empty text box be the default regex. But I'm not super opposed to making a check box either.)

**Comment by rfindler** [comment]
I don't like the empty text box as default regexp. It seems confusing.  (in
the sense that only people who read the manual (ie no one) will understand
the behavior)

**Comment by LeifAndersen** [comment]
I would agree, although I feel like the confusion here could be avoided by having the default regex displayed in a grayed out text when the box is empty would communicate that to the user, without adding an extra button to needlessly make things more complicated. (One of the things I really like about DrRacket is how simple everything is, even the Preferences dialog. And I'd be hesitant to add new buttons or checkboxes or nobs or switches.)

Either way though, after looking at this a bit, it seems like it would be somewhat complicated to change this behavior of the preferences to have a default state, and probably should be separate from this issue, as it really should apply to all of the defaults, not just this one.

(Namely, it seems to me that a better architecture would be to have no defaults written to a settings file, or to have a separate user settings file, that way all of the defaults can be changed without worrying about our current users not getting the update.)

**Comment by rfindler** [comment]
Oh yeah! Greyed out default would be great. People are used to that from
the web! Good idea. :)

**Comment by rfindler** [comment]
Oh, as far as the architecture comment goes, I think that makes sense
for some preferences and not others. Currently you can implement that
yourself with the preferences system, but it also makes sense to me to
add that as an option to `preferences:set-default`.

**Comment by LeifAndersen** [comment]
Ah, yup, I agree. I'll see if I can set that up for this preference. If it goes well we can try to generalize it?

**Comment by rfindler** [comment]
Sure!

**Comment by LeifAndersen** [comment]
Wait, so looking at it right now, it looks like it's already what we suggested it should be.

(Namely, if the user has not modified the preferences, then it doesn't get written to the preferences file.)

**Comment by LeifAndersen** [comment]
Yeah, I just blew away my preferences file, and reconfigured everything (except my tabs), and the property never got added to the preferences file. So that makes me think that indeed, the only people who won't get the update, are the people who changed it on there own anyway. And that's fine, as those people probably wanted there own preferences anyway.

**Comment by LeifAndersen** [comment]
Okay, I made a PR, so I'm closing this issue, and we can talk about it there if needed.

https://github.com/racket/gui/pull/27

**Comment by rfindler** [comment]
I think that's not promised by the library and perhaps could be considered
a bug since it will do that sometimes and not do it other times. Hm. Not
sure how to fix that, actually.
