### ISSUE TITLE
Can not input Chinese by Microsoft Pinyin in windows10 2004

### ISSUE THREAD

**Issue by ghost** [racket/drracket#375]
can not input Chinese by Microsoft Pinyin in windows 10 2004.
DrRacket version: racket-7.7-x86_64-win32-cs.exe

**Comment by sorawee** [comment]
What version of Racket are you using? @mflatt said that the bug was fixed in Racket 7.6. Isn't that the case?

**Comment by BearJean** [comment]
sorry,racket-7.7-x86_64-win32-cs.exe

**Comment by BearJean** [comment]
> What version of Racket are you using? @mflatt said that the bug was fixed in Racket 7.6. Isn't that the case?

But that happens again in the new version

**Comment by mflatt** [comment]
Thanks for the report! Since Windows 10 2004 is now out for everyone, I have been able to debug this. A repair will be in the next snapshot build.
