### ISSUE TITLE
double titlebar 

### ISSUE THREAD

**Issue by spdegabrielle** [racket/drracket#377]
Double toolbar effect

![image](https://user-images.githubusercontent.com/108047/81224545-c7c0c600-8fdf-11ea-878e-05f9ff99b02e.png)

macOS catalina, DrRacket CS 7.7

actions taken:
* removed all other racket installs
* removed plugins/packages
* reset/deleted preferences
* removed /Users/spdegabrielle/Library/Racket (renamed to Racket-old)

**Comment by rfindler** [comment]
How does it look if you create a second tab?

**Comment by spdegabrielle** [comment]
![image](https://user-images.githubusercontent.com/108047/81224997-7107bc00-8fe0-11ea-8ded-75a0cf32c703.png)

**Comment by mflatt** [comment]
@rfindler It's much weirder than that. Even 
```
#lang racket/gui

(send (new frame%
           [label "Test"]
           [width 300]
           [height 300])
      show #t)
```
apparently has the extra title line when run in DrRacket. (I haven't yet replicated the problem, but I'm updating my Catalina installation.)

**Comment by spdegabrielle** [comment]
![image](https://user-images.githubusercontent.com/108047/81225072-8e3c8a80-8fe0-11ea-8dc8-a622c8466da8.png)
affects gui programs run in DrRacket , but not when run from command line with `gracket`.

**Comment by mfelleisen** [comment]
I am on Catalina (just updated to the last patch) and head of Racket (built from source last night), and I don't seethes.

**Comment by mflatt** [comment]
I was not able to provoke this behavior by updating, either.

**Comment by spdegabrielle** [comment]
I’m not sure what else to purge. I was messing with DrRacket/framework following the instructions in the how to contribute to racket blog post, but I have deleted everything.(see earlier comment)

**Comment by samth** [comment]
Can you download a whole new installation of Racket 7.7, and see if the problem re-appears there? (But don't delete the broken install.)

**Comment by spdegabrielle** [comment]
Renamed the broken instance folder
downloaded 7.7 bc
![image](https://user-images.githubusercontent.com/108047/81231993-02c8f680-8fec-11ea-8846-c0ed8780aaa5.png)
same behaviour

**Comment by spdegabrielle** [comment]
tried 7.4 too. I think I can close this as not a racket bug, but rather a configuration quirk with my machine. Apologies for taking up your time.  
![image](https://user-images.githubusercontent.com/108047/81232505-f2654b80-8fec-11ea-9aad-a027976deb5b.png)

**Comment by sorawee** [comment]
https://quality.livecode.com/show_bug.cgi?id=21190 seems to have the exact problem (see the attached screenshot there). It looks like your "Dock -> Prefer Tabs when opening documents -> "Always"" is on, which causes the issue.

**Comment by spdegabrielle** [comment]
My apologies to all who helped.

**Comment by sorawee** [comment]
Well, I do think it's a DrRacket bug. It should handle this configuration better. Here's how Chromium fixes the problem: https://chromium.googlesource.com/chromium/src/+/5788338a8a54e230ef868e66c4ab309bb76dfd65%5E%21/#F1

**Comment by spdegabrielle** [comment]
OK I'm happy with re-opening.

**Comment by mflatt** [comment]
Although I couldn't replicate the behavior, I pushed a change to disable `allowsAutomaticWindowTabbing`.

**Comment by spdegabrielle** [comment]
I think I must have triggered it by using shift-command-T at some point when aspell keybinding was inactive. I was looking at the colorer using 7.7nightly to inspect a cloned drracket in 7.6

**Comment by spdegabrielle** [comment]
>  I pushed a change to disable allowsAutomaticWindowTabbing.
Thanks you. I'll try the nightly tomorrow.

**Comment by spdegabrielle** [comment]
resolved!
