### ISSUE TITLE
DrRacket / Linux: File Permission Error

### ISSUE THREAD

**Issue by Vd86xkht** [racket/drracket#387]
![Screenshot_20200603_112700](https://user-images.githubusercontent.com/44922552/83620213-4d0eaa80-a58d-11ea-96be-009b6c6900d6.png)

Linux: openSuse Tumbleweed.

Sequence:
[1] Start and run `drracket` with user permissions
[2] Type: `#lang slideshow`
[3] Press Run

Information for package racket:
-------------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : racket
Version        : 7.3-2.11
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 260.8 MiB
Installed      : Yes
Status         : up-to-date
Source package : racket-7.3-2.11.src
Summary        : Scheme implementation with teaching tools

**Comment by spdegabrielle** [comment]
Thanks for reporting. 

Can you try to reproduce with the current version? (7.7)

The current version can be downloaded from https://download.racket-lang.org

Kind regards

Stephen

**Comment by Vd86xkht** [comment]
It seems fixed in version 7.7

![Screenshot_20200603_132913](https://user-images.githubusercontent.com/44922552/83631702-39b80b00-a59e-11ea-956b-5c41a4eb41ac.png)

**Comment by spdegabrielle** [comment]
Good to hear.  if you are happy please close the issues.

if you need further help Racket discussion can be found on
   
  - [racket-users](https://groups.google.com/forum/#!topic/racket-users) Mailing list/google group
  - https://racket.slack.com/ (Sign up at https://racket-slack.herokuapp.com/ )
  - `#racket` IRC on freenode.net https://botbot.me/freenode/racket/

A bunch of other resources are at https://racket-lang.org

Stay well

Stephen
