### ISSUE TITLE
The example in hyper.rkt does not work

### ISSUE THREAD

**Issue by Domon** [racket/drracket#4]
I found the example in [hyper.rkt](https://github.com/racket/drracket/blob/8700d736e95f0c360afca9528a815bd75a1252cc/drracket/browser/private/hyper.rkt) does not work.

To be more specific, the canvas does not load:

![dr-racket-hyper-rkt-example](https://cloud.githubusercontent.com/assets/69308/7181544/226542a6-e47e-11e4-8b57-de7503db175a.png)

The following is the code of the example:

``` racket
#lang racket
(require racket/gui browser framework)

(define f%
  (frame:status-line-mixin 
   frame:basic%))

(define f (new f%
               (label "My Frame")
               (width 400)
               (height 300)))
(define browser (new hyper-panel% 
                     (info-line? #f)
                     (parent (send f get-area-container))))
(send f show #t)

(send (send browser get-canvas)
      goto-url
      ;; The starting URL:
      "http://www.htdp.org/";
      ;; #f means not a relative URL:
      #f)
```

It seems that `goto-url` only works if the `top-level-window` is a `hyper-frame%`. (See 
[line 697](https://github.com/racket/drracket/blob/8700d736e95f0c360afca9528a815bd75a1252cc/drracket/browser/private/hyper.rkt#L697) of `hyper.rkt`.)

I am still learning how to use this library, so I am not sure if this should be fixed or is by design. I am willing to help if there are anything I could do.

Thanks! :smile:

**Comment by dertuxmalwieder** [comment]
Confirmed, still not working with the latest versions (Windows 10).
