### ISSUE TITLE
Context lost when saving new files.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/drracket#40]
This is probably a minor annoyance, but when saving a new file, DrRacket should probably use the directory of the last open file to save the file, rather than `current-directory`. (And only use `current-directory` if it's the only file open.

The reason I say this is because I've now found several times that I am starting a project where I want to create several files, and it's very annoying to constantly navigate to my project directory when saving a new file.

Another option would be to make `current-directory` be the directory of the last open file, but I don't like that because then it becomes harder to trust where the `current-directory` is.

**Comment by rfindler** [comment]
This is controlled by your OS not DrRacket. At least on most OSes.

Robby

**Comment by LeifAndersen** [comment]
Oh? I knew those dialogs were handled by the OS, but I thought they took an argument for what directory to initially open up to.

(A different thing that might be nice would be to just have our own dialog that allows us to just type in a path. But I could probably just do that as a plugin.)

**Comment by LeifAndersen** [comment]
Yeah, it looks like the function call `get-file` allows you to pass in a starting string.

**Comment by LeifAndersen** [comment]
Also, lol, common is exactly what I was looking for.

(I really hate the OS X file dialog.)

**Comment by rfindler** [comment]
FWIW, I think it is important than nothing be passed as that argument so
that the OS gets to control the default value.

Also: are you starting DrRacket by clicking in the Finder? Or are you
running it from the command-line? The former might change the behavior, I'm
not sure.

**Comment by LeifAndersen** [comment]
I am either opening it with the open command on OS X, or using spotlight. (I do both.)

**Comment by rfindler** [comment]
Oh, okay. Those should be the same as double-clicking, I think. Rats.

**Comment by rfindler** [comment]
@LeifAndersen : given that I feel like the OS should be in charge of this choice (since the dialog is doing a lot of stuff), I'm inclined to close this PR. But is there is something else I can do to help you wrt DrRacket along these lines somehow? 

Does it help to point out that the "Open Require Path ..." dialog lets you start with a double quote and then you get a different way to navigate locally that you might like better?

**Comment by wangjiezhe** [comment]
Mmm... I think I'm going to the same problem.
Is there any simple way to open a new tab and save it in the directory of the previously opened file?

**Comment by rfindler** [comment]
In version 10.14.6 of macOS and a recent git build of DrRacket, creating a new tab, saving it (following a navigation to some far away directory), creating a new tab, and then saving it, results in the second save starting in the directory where the first save started.
