### ISSUE TITLE
Arrays in syntax parse template seem wrong

### ISSUE THREAD

**Issue by pmatos** [racket/drracket#403]
Run:

```
#lang racket/base

(require (for-syntax racket/base syntax/parse))

(define-syntax (f stx)
  (syntax-parse stx
    #:track-literals
    #:datum-literals (& = xx)
    [(_ k:exact-positive-integer n:exact-nonnegative-integer)
     #'(* 2 n k)]
    [(_ _ (xx n:exact-nonnegative-integer k:exact-positive-integer))
     #'(* 3 n k)]
    [(_ k:exact-positive-integer name:id)
     #'(string-length (string-append (symbol->string 'name) (number->string k)))]
    [(_ k:exact-positive-integer (& a:expr ...+))
     #'(min (f k a) ...)]
    [(_ k:exact-positive-integer (= a:expr ...+))
     #'(max (f k a) ...)]))
```

Press Run (version 7.8 both BC and CS), and see the arrows for `k` in the last couple of patterns actions. They seem to be wrong. Here's a screenshot.

![2020-08-05-074704_1089x501_scrot](https://user-images.githubusercontent.com/7911/89376524-3e10b980-d6f0-11ea-9fe7-66d2f08740eb.png)

**Comment by pmatos** [comment]
Please let me know if this is not the right place for this bug. First time I see a problem in this area so unsure if it belongs here on in `racket/racket`.

**Comment by sorawee** [comment]
It's the same as racket#1875 I think?

**Comment by pmatos** [comment]
> It's the same as [racket/racket#1875](https://github.com/racket/racket/issues/1875) I think?

You're right. Totally confusing in this example because there doesn't seem, at first, glance why it would point to the third pattern `k` and not, let's say, the first `k`

Anyway, I will close this as a dup.

Duplicate of https://github.com/racket/racket/issues/1875
@mflatt please reopen if you don't think that's the case.
