### ISSUE TITLE
update logo in lang config guidance dialog

### ISSUE THREAD

**Issue by spdegabrielle** [racket/drracket#404]
![image](https://user-images.githubusercontent.com/108047/89408377-2ea56680-d718-11ea-88aa-20105385b17c.png)

**Comment by spdegabrielle** [comment]
I'll get to this before 7.9 but - if you want to do this just leave a note here. (it should be very simple)

**Comment by thuttner** [comment]
I want to do that :)

**Comment by spdegabrielle** [comment]
Go for it!

**Comment by thuttner** [comment]
@spdegabrielle I need some help. Where is the right place to ask? I found the file where the dialog is generated and replaced the old logo with the new one. But when I run drracket there is still the old logo :(

**Comment by spdegabrielle** [comment]
Have you rebuilt the `DrRacket` package with `raco setup`


https://github.com/racket/racket/wiki/Propose-a-fix-or-enhancement wiki page links to resources - check 'How to contribute to a main distribution package' in the blog post for an introduction

**Comment by thuttner** [comment]
@spdegabrielle Thanks for the guidance! :+1:

**Comment by spdegabrielle** [comment]
closed with thanks to @thuttner

**Comment by thuttner** [comment]
The final solution, wasn't me. Thanks has to go to @rfindler  :)
