### ISSUE TITLE
Setting for no cache directories

### ISSUE THREAD

**Issue by guygastineau** [racket/drracket#409]
Hello, I have some colleagues using DrRacket as their IDE while using tools I build for the team in Racket.  I use Emacs, so I had never realized that DrRacket makes cache directories called `compiled` everywhere that it loads required source modules.

Is there a way to turn that off or to set a specific directory as the home of all cached compilations?  I would prefer not adding a new rule to `.gitingore`.  I don't mind just turning the caching off if that is the only thing to do, I just don't want the compiled directories all over the place.

Thank you for your help.

**Comment by rfindler** [comment]
To disable this, choose Language | Choose Language, then "Show Details..." then uncheck the checkbox labelled "Populate ....". 

These compiled directories aren't only created by DrRacket however. If you ever set up a collection (via a pkg) or you use raco make (which can speed up loading your program significantly depending on the size of your code), you will find them reappearing.

**Comment by guygastineau** [comment]
Thank you very much for the quick response.

It is essentially an SDK I make for my team, and the loading times are not an issue.

**Comment by guygastineau** [comment]
Just to be clear, you make a compelling case for adding a rule to all `.gitignore` files for racket projects to handle these cache directories, so thank you for that ;)
