### ISSUE TITLE
Line highlting broken on line wrap.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/drracket#41]
If I have a file with a line that line wraps to multiple files, DrRacket has trouble drawing the arrow that indicates the active line numbers. You end up seeing things like the attached image.

(I am sorry about all of the issues I've reported recently without solutions...)

![screen shot 2016-02-18 at 6 04 57 pm](https://cloud.githubusercontent.com/assets/285926/13161225/620eef22-d66a-11e5-8824-8be545f5ee13.png)

**Comment by LeifAndersen** [comment]
(Also, yes, I used the wrong there in that screenshot. :( )

**Comment by rfindler** [comment]
I think that this is a bug in the code that decides which region to
invalidate as the insertion point changes.

The relevant code is in framework/private/text in the implementation of
line-numbers-mixin

Do you want to have a look? Let me know if you get stuck?

**Comment by LeifAndersen** [comment]
I'm working on my paper at the moment, and the next thing in my, 'I need a break so I'm going to hack' queue is the scribble indentation bug, but I'll take a look at it after that. (Probably in a week or two.)

Thank you for pointing me to where I need to look.

**Comment by rfindler** [comment]
I am not able to reproduce this any more. Yesterday I saw something similar but not the same as what you see and today I am not able to provoke bad behavior and looking at the code, I'm not seeing anything that would suggest it is wrong.

So I have no plans to investigate this further.

**Comment by samth** [comment]
@LeifAndersen if you want a test case, I was able to produce some slightly different drawing issues than your screenshot shows as follows:

1. Paste the following into a fresh editor buffer:

```
#lang scribble/base


a b c d e f g

xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

2. Put the cursor on the `#lang` line.
3. Move the cursor up and down. Once you move off of the long line, some parts of the triangles are still there (the left side, and the bottom of the last one).

**Comment by rfindler** [comment]
Turns out the missing piece was that you need to have to font set suitably large (or, more technically, set to a size that is more obviously different from the settings in the dc, whatever font that is)

**Comment by rfindler** [comment]
Oh, crap. My commit that fixes this is here and it probably closed the wrong issue because this is the wrong repo: https://github.com/racket/gui/commit/c8c8ce64eb5f18d770c06997a3164f5d64f03c24
