### ISSUE TITLE
DrRacket contour menu both slow, and locks up gui.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/drracket#42]
If I'm editing a large file in DrRacket (say 2,000-3,000 lines), and I scroll up or down in the countor menu, it moves up and down extremely slowly. Worse still though, while it's moving, it locks up the GUI so that I cannot scroll up or down myself until it stops. (Which will be long after I stopped scrolling.)

**Comment by rfindler** [comment]
The new implementation of the contour window (that is overlaid on the program text instead of in a separate window) is a lot faster and does not have this problem, I believe. If I'm wrong about that, please reopen this issue.
