### ISSUE TITLE
bug in check syntax

### ISSUE THREAD

**Issue by yjqww6** [racket/drracket#425]
Paste the following program into DrRacket, press the "Check Syntax" button.
```racket
#lang racket
(require (for-meta 2 racket/base))
(begin-for-syntax
  (begin-for-syntax
    (module a racket/base)))

```
No arrows or highlights for identifier `module` and identifiers inside submodule a. 
Also, `racket/base` in the "for-meta 2" require is red, but its bindings are indeed used.

I am using racketcs 7.8.

---
https://github.com/racket/drracket/blob/1b89271ed1843ac501abcd8476cbf4d8603cf52d/drracket-tool-lib/drracket/private/syncheck/traversals.rkt#L404
https://github.com/racket/drracket/blob/1b89271ed1843ac501abcd8476cbf4d8603cf52d/drracket-tool-lib/drracket/private/syncheck/traversals.rkt#L417 
From my previous experience, simply matching `#%plain-module-begin` in the same phase with `module` is problematic.
And it seems replacing `#%plain-module-begin` with `_` solves this problem.

**Comment by rfindler** [comment]
Thank you!
