### ISSUE TITLE
Interface hangs when blue boxes load

### ISSUE THREAD

**Issue by Fictitious-Rotor** [racket/drracket#428]
Blue boxes load on the main thread, causing the interface to hang on startup (after typing your first function name)

Instructions to repeat:
1. Launch DrRacket
2. Type "thread" in the definitions window
3. Continue to type

You will notice that the text typed after the keyword will not appear until the blue box loads.

**Comment by rfindler** [comment]
I believe that this commit fixed that: 2db3b665af50027afabf3e57c9f4b49da96f87b8. Are you using v7.8?

**Comment by Fictitious-Rotor** [comment]
I hadn't realised that the version of the ide built from source was dependent on the version of racket with which you launch it.
Hopping between the 7.6 and 7.8 racket executables I seem to get different versions of the application from the same source code.

However this issue is indeed resolved for me when using v7.8, thank you!
