### ISSUE TITLE
Improper indentation of (let ([define-foo \n 'test]) …) with #lang scribble/lp2

### ISSUE THREAD

**Issue by jsmaniac** [racket/drracket#44]
In the following program, the expression bound to `define-foo` is improperly indented

```
#lang scribble/lp2

@chunk[<*>
       (let ([define-foo
 'test])
         define-foo)]
```

Using `#lang racket`, the expression is indented as expected:

```
#lang racket

(let ([define-foo
        'test])
  define-foo)
```

This happens only with identifiers that match the "keywords that look like Define" regexp (or list), from the preferences. The actual code I have is binding `define-foo` with `splicing-syntax-parameterize`, which explains the otherwise weird name.

I am using today's 6.4.0.8 build (20160226-15f47ef).

**Comment by rfindler** [comment]
Thank you for your interest. This is the wrong repo, tho. The code is actually here:

https://github.com/racket/gui/blob/master/gui-lib/scribble/private/indentation.rkt

**Comment by jsmaniac** [comment]
This issue was moved to racket/gui#28

**Comment by jsmaniac** [comment]
@rfindler Thanks, I moved the issue.
