### ISSUE TITLE
[Feature Request] Addition of "c:?" and "c:!" as new keybindings in DrRacket editor

### ISSUE THREAD

**Issue by encomer** [racket/drracket#454]
**Problem Situation:**
The use of the inverted symbols "?" and "!" , are often required when using english keyboards, but in DrRacket editor we don't have the option to use the ALT-[number] for the corresponding codes.

**Suggestion:**
Consider the addition of the following keybindings in the default configuration of DrRacket:
```
#lang s-exp framework/keybinding-lang
(keybinding "c:?" (λ (editor evt) (send editor insert "¿")))
(keybinding "c:!" (λ (editor evt) (send editor insert "¡")))
```
This would be very useful in order to use this keybindings in an online course, and avoiding the need to add them in some of the computers in the group.

Thank you very much for considering this request.
_Please Keep Safe_.
Enrique

**Comment by rfindler** [comment]
@encomer I've transferred the issue to the DrRacket repo. I really don't think it makes sense to add these keybindings to a default install of DrRacket. There are many users of DrRacket out there and many different keyboards and configurations that the OS is in control of. Changing them at the "last mile" is surely going to wreck someone else's use of DrRacket. 

I think probably best to give instructions to your students to use the [Edit|Keybindings|Add User-Defined Keybindings... menu item](https://docs.racket-lang.org/drracket/Keyboard_Shortcuts.html#%28part._defining-shortcuts%29).

**Comment by encomer** [comment]
Thank you very much @rfindler . I will do as you said. 
_Congratulations to all of you for the great collaborative work_.
