### ISSUE TITLE
font size inconsistency

### ISSUE THREAD

**Issue by sorawee** [racket/drracket#463]
Consider:

```
#lang racket
(add1 (let loop ([n 5])
        (cond
          [(zero? n) (/ 1 0)]
          [else (add1 (loop (sub1 n)))])))
```

The backtrace displays:

<img width="818" alt="Screen Shot 2021-02-03 at 8 49 41 PM" src="https://user-images.githubusercontent.com/9099577/106846380-9e61c300-6661-11eb-9c39-778cddc21d9c.png">

Notice that 
- the size of the first srcloc is different from the size of other srclocs
- the size of most srclocs are different from the size of "skip duplicate frames"
- srclocs have a space between source name and line&column, which is not how srclocs are usually formatted.

It's unclear what is the desired outcome, but it definitely should not be inconsistent like this.

**Comment by rfindler** [comment]
They should all be like the first one, IMO.
