### ISSUE TITLE
Cannot reclick step button in debug mode.

### ISSUE THREAD

**Issue by benkwokcy** [racket/drracket#470]
Problem:
When in debug mode, if I click "step", it will work once but the button will become unclickable (as in, it will not be highlighted and clicking on it has no effect). To re-click the button, I have to move my cursor off the button and then back to the button. Then it will work again. The same behavior happens with the "go" button.

[Here](https://user-images.githubusercontent.com/32286298/109915376-94ce7980-7c66-11eb-93b3-6f7b2334f1b9.gif) is a gif showing the bug.

Steps To Reproduce:
1. Write any code in DrRacket.
2. Enter debug mode.
3. Set a breakpoint.
4. Press "go" with your mouse.
5. Press "step" with your mouse and leave the cursor on the button.
6. Try to press "step" again.

Environment:
MacOS Mojave (10.14.6)
DrRacket, Version 8.0 (CS)

**Comment by sorawee** [comment]
IIUC, this is fixed by https://github.com/racket/gui/commit/6248904d28b8846436e81e0f1424a262d18e4d9a. Can you confirm that it's actually fixed now by trying a snapshot version (http://snapshot.racket-lang.org/)?

**Comment by sorawee** [comment]
IIUC, this is fixed by https://github.com/racket/gui/commit/6248904d28b8846436e81e0f1424a262d18e4d9a. Can you confirm that it's actually fixed now by trying a snapshot version (http://snapshot.racket-lang.org/)?

**Comment by benkwokcy** [comment]
I just tried the snapshot version and it's fixed! (for reference, I used MacOS 64-bit Intel)

**Comment by sorawee** [comment]
Cool! :) I will close the issue then.
