### ISSUE TITLE
Latex unicode table should be public somewhere

### ISSUE THREAD

**Issue by willghatch** [racket/drracket#48]
After discussing how there is no good way to enter unicode, I made a handy little Racket program to enter unicode in any window.  But in addition to the long official descriptions of unicode characters, I wanted to use DrRacket's table of Latex-stolen names.  So I copied drracket/browser/private/entity-names.rkt into my project (providing the table itself instead of just the access function).  But I would really love to just require it from a public place, either in the drracket package itself or in another package they can both depend on.

**Comment by rfindler** [comment]
mrlib/tex-table in the gui pkg?

**Comment by willghatch** [comment]
Well now I feel dumb.  That file will be great.  So what's the difference supposed to be between tex-table and that entity-names file I found?

**Comment by rfindler** [comment]
I think the file you found is part of a long-defunct web browser implementation that we used to display docs a very long time ago.
