### ISSUE TITLE
When creating a standalone executable for MacOS, DrRacket says "for this machine only". But can't any other machine with the same OS and architecture also run the executable?

### ISSUE THREAD

**Issue by seisvelas** [racket/drracket#493]
I open DrRacket and click Racket -> Create Executable. DrRacket implies I am making an executable just for my own machine - but shouldn't the resulting executable work on any machine? I know it's not the normal way to use software on MacOS, but if I made an executable that way, host it on a webserver, you `wget` and run it, shouldn't that work just fine?

<img width="448" alt="Screen Shot 2021-06-17 at 6 36 05 p m" src="https://user-images.githubusercontent.com/44826516/122488533-e0e5c580-cf9a-11eb-89cf-05711c074082.png">

**Comment by alex-hhh** [comment]
"for this machine only" means that the resulting executable will need to use Racket libraries from the racket installation.  It will run on any machine which has:

* same OS
* same architecture
* same Racket version, same Racket architecture (cs or bc) and it is installed in the same place.

You need to select "distribution", which will produce an executable plus associated libraries.  This executable will run on other machines with the same OS and architecture even if that machine does not have Racket installed.

**Comment by seisvelas** [comment]
Aha! Thanks. When I do that, it generates a .dmg, but the only thing the .dmg appears to contain is the executable. So, would this work:

1. Create the .dmg using the distribution option
2. Extract the executable from the resulting dmg
3. Distribute that executable by itself to other users on the same OS an architecture

?

**Comment by alex-hhh** [comment]
I don't know the answer to that question.  It is MacOS specific and I don't use MacOS.

I would suggest you ask these questions either on the racket users group or the slack channel, as there are other people there who use MacOS and are able to help (and those people usually don't monitor this issue tracker).

**Comment by samdphillips** [comment]
DMG files are one of the standard distribution mechanisms for Mac OS.  The executable inside is actually a folder.  It's generally easier to just distribute the DMG and tell the user to drag the "Application" out of the DMG and put it where they want on their computer.

**Comment by seisvelas** [comment]
Thanks! So the bin/executable file inside the dmg should run just take it out and distribute it directly, instead of distributing the .dmg, if I understand you correctly. 

Yay! Go Racket! Best community of all time <3
