### ISSUE TITLE
Ctrl+Shift+T to open previously closed tabs 

### ISSUE THREAD

**Issue by jestarray** [racket/drracket#508]
It seems like racket has adopted `ctrl+T` for new tab, `ctrl+W` for close tab, similar to browsers like ff and chrome, however `ctrl+shif+T` is not bound to opening a recently closed tab? I've been using `ALT+F T` for a while now

**Comment by rfindler** [comment]
This would be a really good one to add. I often miss it as well. The "File|Open Recent" menu's top most item is an approximation of that, but not exactly the same (it will be the most recently visited tab)

**Comment by sorawee** [comment]
FWIW, I created https://docs.racket-lang.org/drracket-restore-workspace/ that implements this functionality (more or less). You need to create a keybinding yourself however.

I believe @Metaxal also implemented something similar with Quickscript.

**Comment by sorawee** [comment]
Oh no, I misread the thread, sorry. Mine restores the entire workspace. The requested feature here restores only one tab.

**Comment by Metaxal** [comment]
It should be mostly straightforward to adapt the open-recent quickscript to
your needs:
https://gist.github.com/Metaxal/0bbd874891442aad78fbd0c08a329cd9

If you do write such a script, it would be great if you could share it on
the wiki:
https://github.com/racket/racket/wiki/Quickscript-Scripts-for-DrRacket

**Comment by squarebat** [comment]
@Metaxal sorry for the delay, couldn't look into this due to exams. I couldn't fix it by upgrading for some reason, but a clean install did the trick! The script works as expected. I will look into how to add that change to the gui repo.
