### ISSUE TITLE
Split off module browser from `drracket-tool-lib` to a new `drracket-tool-lib-gui` package?

### ISSUE THREAD

**Issue by greghendershott** [racket/drracket#517]
I've been looking at packages that depend on `gui-lib` when maybe they need/ought not to.

One is `drracket-tool-lib`. However "most" of it doesn't use `racket/gui/base`. I think the only portions that do are two modules:

- https://github.com/racket/drracket/blob/master/drracket-tool-lib/drracket/module-browser.rkt
- https://github.com/racket/drracket/blob/master/drracket-tool-lib/drracket/private/standalone-module-browser.rkt

Would it be possible move those two files into their own package, called (say) `drracket-tool-lib-gui`, and adjust the `drracket-tool` meta package?

IIUC the files would move within this git repo, and get their own package `info.rkt` and node on `pkgs.racket-lang.org` --- but the collection paths would remain the same so they'd still end up installed in the same place and nothing would break. I think. Does that seem correct?

**Comment by rfindler** [comment]
Thanks, @greghendershott
