### ISSUE TITLE
Automatically dismiss message panel when there are no more errors

### ISSUE THREAD

**Issue by aymanosman** [racket/drracket#528]
<img width="959" alt="Screenshot 2021-11-15 at 15 28 38" src="https://user-images.githubusercontent.com/3605049/141808776-b95c4d68-bf62-425e-be66-1f81bb40f461.png">
<img width="959" alt="Screenshot 2021-11-15 at 15 27 17" src="https://user-images.githubusercontent.com/3605049/141808763-33831dc7-12fc-4346-bbdd-4f00a2e0a168.png">

Currently, the user has to manually click the "close" button to dismiss the area where the old error message was displayed. Should this not automatically happen?

If this sounds like a reasonable thing to do, then I would be happy to implement it if I could get some pointers.

**Comment by sorawee** [comment]
Duplicate of #379?

**Comment by aymanosman** [comment]
Yes. Closing this one.

**Comment by rfindler** [comment]
@aymanosman I would be happy to provide pointers (in the other issue) if you find that one of the (well-liked) ideas there resonates with you.
