### ISSUE TITLE
Snapshot: Errors on right-click

### ISSUE THREAD

**Issue by Metaxal** [racket/drracket#536]
Version: 8.3.0.10--2021-12-07(2a842c9aa0/a) [cs] installed from racket-test-8.3.0.10-x86_64-linux-precise-cs

Right clicks don't work anymore, I can't even copy the text of the error message:
![Screenshot from 2021-12-08 12-21-54](https://user-images.githubusercontent.com/1658140/145207807-d8737761-4a5f-4416-ab1a-32e2b4b49d45.png)
![Screenshot from 2021-12-08 12-23-38](https://user-images.githubusercontent.com/1658140/145207852-83b4a962-6769-4873-87de-6506ca2e1728.png)

**Comment by Metaxal** [comment]
To reproduce:
```racket
#lang racket
(define x 3)
```
Right click on `x`, or on `racket`.

**Comment by mflatt** [comment]
Thanks for the report! It looks like I missed a change when committing repairs for Gtk/Wayland as couple of weeks ago.

**Comment by Metaxal** [comment]
Thanks for the quick fix!
