### ISSUE TITLE
Racket -> Enable Tests should be hidden when not in teaching languages.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/drracket#54]
When using DrRacket in the mode where it uses `#lang` to determine the language, the menu option `Racket -> Enable/Disable Tests` shows up. When it is set to have tests disabled, they still seem to run. Including:

* The `test` submodule still runs
* Rackunit tests still run
* `test-engine/racket-tests` still run.

This is very confusing as this button doesn't seem to do anything.

There is a button to disable the test submodule in the Language preferences menu, which does seem to work as expected.

It seems to me that we should either remove the button when not using a teaching language, or set it to enable/disable the test submodule.

**Comment by rfindler** [comment]
This was caused by a menu item added by a teaching languages' tool. I've added a message to clarify that yes, in fact, it doesn't do anything.

https://github.com/racket/htdp/commit/491e8037ccde630d3e57eb2b460fb4b32f84f45b
