### ISSUE TITLE
DrRacket scribble pdf - could not find a pdflatex executable

### ISSUE THREAD

**Issue by maymunashah** [racket/drracket#553]
I am new to dr racket and was trying to use scribble documentation. Scribble html works perfectly for me but I tried to use scribble pdf button available to me but it gives me this error. 

Welcome to DrRacket, version 8.4 [cs].
Language: scribble/base, with debugging; memory limit: 128 MB.
scribble: loading xref
scribble: rendering
. . C:\Program Files\Racket\share\pkgs\scribble-lib\scribble\private\run-pdflatex.rkt:77:0: run-pdflatex: could not find a `pdflatex' executable

Any idea how to resolve this.
Btw. Im using windows 10.

**Comment by jryans** [comment]
`pdflatex` is not included with Racket, so you'll need to install that separately if you to generate PDFs. There are various options available, perhaps a LaTeX distribution from https://www.latex-project.org/get/ is a good path to try.

**Comment by soegaard** [comment]
Yes, download a TeX distribution.

I can recommend TeX Live:
https://tug.org/texlive/

**Comment by maymunashah** [comment]
> `pdflatex` is not included with Racket, so you'll need to install that separately if you want to generate PDFs. There are various options available, perhaps a LaTeX distribution from https://www.latex-project.org/get/ is a good path to try.


You were right i actually hadn't installed latex. I installed latex, copied pdflatex file from mktex directory and pasted in racket files.  i can now generate pdfs easily. Bundle of thanks 😊

**Comment by maymunashah** [comment]
> Yes, download a TeX distribution.
> 
> I can recommend TeX Live:
> https://tug.org/texlive/

I actually did mktex and it works now. Thankyou!
