### ISSUE TITLE
Text is not displayed until you click on it in Help→About

### ISSUE THREAD

**Issue by rrthomas** [racket/drracket#577]
Tested with Racket 8.5 from the PPA on Ubuntu 22.04 with a GNOME desktop running with dark theme. Screenshot attached after a few random clicks in the window to show some lines of text drawn.

![Screenshot from 2022-08-19 16-39-41](https://user-images.githubusercontent.com/17382/185643693-fd37d3c3-c819-4b25-b8ba-2ebcdcf11288.png)

To clarify: when the window is first opened, no text is visible. Each time I click in the window (or click+drag), the line of text at that position is drawn (or drawn and highlighted, respectively).

**Comment by sorawee** [comment]
It affects Mac OS too (I have seen this issue for a while now but keep forgetting to report)

**Comment by rrthomas** [comment]
Thanks for the quick fix, @rfindler!
