### ISSUE TITLE
Background expansion terminated abnormally (out of memory)

### ISSUE THREAD

**Issue by sorawee** [racket/drracket#580]
```
#lang typed/racket

(struct S ([elem : (S Number -> Number)]) #:prefab)

(: get-val (-> S Number Number))
(define (get-val x y)
  y)

(S get-val)
```

fails with:

```
Background expansion terminated abnormally (out of memory)
```

Reported by user CalvinX on Discord.

**Comment by samth** [comment]
Yeah that looks like an infinite loop in the printer.

**Comment by samth** [comment]
Most likely printing a recursive `#:prefab` type tries to print the type again.

**Comment by samth** [comment]
Changing the last line to `(S 1)` causes expansion (not just background expansion) to fail to terminate. I think the original program is diverging when trying to produce tooltips.
