### ISSUE TITLE
Show the X button for exn:fail:user with prop:exn:srclocs

### ISSUE THREAD

**Issue by sorawee** [racket/drracket#582]
I have an error that interfaces end users, so I don't want to show the stacktrace (esp. in the command-line). `exn:fail:user` fits this purpose. However, when given `prop:exn:srclocs` on top of `exn:fail:user`, the jump to error "X" button is gone too. It would be nice if that's not the case.

**Comment by sorawee** [comment]
This is the relevant code: https://github.com/racket/drracket/blob/master/drracket/drracket/private/debug.rkt#L369

**Comment by rfindler** [comment]
I'm happy with a slightly different predicate there. Is this the "x" in the REPL you want to show? So you want the call to `display-srclocs-in-error` to happen?

**Comment by sorawee** [comment]
Yes, I want `display-srclocs-in-error` to be called. What I don't know is whether it should be unconditionally called, or whether it should be called for (1) non-`exn:fail:user` OR (2) something with `prop:exn:srclocs`

**Comment by rfindler** [comment]
@sorawee is what I pushed what you have in mind? the program in the test case in the commit message is my attempt to distill the original bug report into a small example.

**Comment by sorawee** [comment]
Yep, that appears to be what I had in mind. So I will close the issue as fixed.
