### ISSUE TITLE
"Kill" button is misleading

### ISSUE THREAD

**Issue by sorawee** [racket/drracket#588]
After we click the "Stop" button, the label is changed to "Kill". This "Kill" seems to have a different meaning from Cmd+K (Force the Program to Quit), however. I'm not totally sure how they are different precisely, but I do know that, for example, clicking the "Kill" button won't invoke the `kill-evaluation` method, but Cmd+K will.

The different behavior is confusing and misleading. They should have the same behavior. Alternatively, there should be three different labels for these three different actions.

**Comment by rfindler** [comment]
I think it does actually shut the custodian down. Is there something else you're missing? Here's what I tried: with this in the definitions window:

```
#lang racket
(break-enabled #f)
(semaphore-wait (make-semaphore 0))
```

I hit run. Then I hit Break and the  button label changed into Kill. Then I clicked Kill and the interactions window was reset. It looks like this is the code that gets invoked when that button is clicked (in either mode): https://github.com/racket/drracket/blob/master/drracket/drracket/private/unit.rkt#L1324

**Comment by rfindler** [comment]
Probably it makes sense to do those things in both cases (so call `kill-evaluation` when clicking on the break-button but it is in "kill" mode).
