### ISSUE TITLE
feature request: each tab preserves size / location of interactions window

### ISSUE THREAD

**Issue by mbutterick** [racket/drracket#59]
In each DrRacket tab, you can hide / show the definitions & interactions panes, and these settings are preserved for each tab.

However, for any tab where both definitions and interactions are visible, the size and position of the panes are the same.

It would be great to make these settings independent per tab, so you could e.g., have a small horizontal interactions pane in one tab, and a large vertical one in another.

**Comment by mbutterick** [comment]
Thank you for adding this. FWIW I just updated Racket from HEAD (v6.6.0.2). The definition / interaction panels retain their size setting on a per-tab basis, but not their orientation. (Meaning, once you make one vertical, they all become vertical.)

**Comment by rfindler** [comment]
Thanks, I've fixed that too.

**Comment by mbutterick** [comment]
That worked, thanks
