### ISSUE TITLE
#; not fading correctly in the menu languages(htdp)

### ISSUE THREAD

**Issue by jestarray** [racket/drracket#591]
One of the students taking the HTC course on edx said this:

> That feeling when you've forgotten to remove the #; and uncomment your code, causing your code to run off of the stub during testing for the past two hours and driving you insane during debugging the sudoku solver.

`#lang htdp/bsl` does fade it out correctly though, just that the menu based ones do not.

**Comment by sorawee** [comment]
See also: https://github.com/racket/syntax-color/issues/13

**Comment by jestarray** [comment]
Oh I did not see that, closing and moving discussion to there!

**Comment by rfindler** [comment]
FWIW, I think this goes in the htdp repo and the one sorawee linked to is
related but a different issue (a problem with the module lexer)

**Comment by jestarray** [comment]
can you transfer this to htdp repo, thanks!
