### ISSUE TITLE
Canvas window cannot be closed with keyboard on OS X

### ISSUE THREAD

**Issue by k4rtik** [racket/drracket#6]
I am reading through HtDP/2e and find it annoying that pressing `Cmd+W` or `Esc` can't close the canvas windows that appears while using the `animate` from `2htdp/universe`. `Cmd+Q`, of course, tries to close the whole DrRacket IDE. The only way it seems is to use the mouse pointer to press the red close button.

**Comment by rfindler** [comment]
I'm not sure how to move this PR, but it is unrelated to DrRacket and belongs on this git repo: https://github.com/racket/htdp

Of course, patches are also welcome.

**Comment by k4rtik** [comment]
Thanks, I will file it there then.

**Comment by samth** [comment]
@rfindler Just for reference, github doesn't have a way of moving bug reports.
