### ISSUE TITLE
HEART LOGO EVERY DAY NOT JUST VALENTINE'S DAY

### ISSUE THREAD

**Issue by t0mpr1c3** [racket/drracket#606]
Now that I know Dr Racket loves me, I want Racket love in my life all year round. <3
![racket-love](https://user-images.githubusercontent.com/1699266/218914497-89ce1e9d-ff78-4bd0-b34e-65e5c3a6617b.png)

**Comment by spdegabrielle** [comment]
That is so sweet!

The community is mostly on the Racket [Discourse](https://racket.discourse.group/) (an open source web forum with no ads or tracking) and [Discord](https://discord.gg/6Zq8sH5)(chat) - this comment would be welcomed there.

If you want to make it run every day, you should check the [DrRacket source](https://github.com/racket/drracket) to see how it works. (And perhaps make your own)

Be careful! If you do make it run every day you might miss out on the other Easter eggs!
(The Ada Lovelace is my favourite.)

I’ll close this for now but very happy to see DrRacket bring you joy😁
