### ISSUE TITLE
DrRacket very slow for text editing after new installation

### ISSUE THREAD

**Issue by spdegabrielle** [racket/drracket#609]
DrRacket very slow for text editing after new installation.
I persisted and it got back to being its snappy self. 

I have a reasonable fast machine mbp/M1/32gb. 

I can try to reproduce by wiping my install, installing 8.7, then reinstalling 8.8. 
Before I do that I've like work out how I can identify the cause. Is there a profiler I can use to get a better idea of what is happening? Maybe something else?

Any advice appreciated.

Stephen

**Comment by rfindler** [comment]
I don't know if it will turn up anything useful but if you start DrRacket with `PLTDRPROFILE` turned on, you can collect profiling information about what's going on in GUI callbacks.

**Comment by LiberalArtist** [comment]
You didn't by any chance install using Homebrew, did you? I don't remember if the issue from [this Discord thread](
https://racket.discourse.group/t/minimal-racket-is-very-slow-before-installing-compiler-lib/967/20) with mtimes and/or `(find-compiled-file-roots)` in an `--enable-origtree=no --enable-macprefix` build was ever resolved.

**Comment by spdegabrielle** [comment]
> You didn't by any chance install using Homebrew, did you? I don't remember if the issue from [this Discord thread](https://racket.discourse.group/t/minimal-racket-is-very-slow-before-installing-compiler-lib/967/20) with mtimes and/or `(find-compiled-file-roots)` in an `--enable-origtree=no --enable-macprefix` build was ever resolved.

I use standard Racket from https://download.racket-lang.org/installers/8.8/racket-8.8-x86_64-macosx-cs.dmg 
then used `raco pkg migrate 8.7`
I'll take a note of what I have installed before I upgrade 
<img width="472" alt="image" src="https://user-images.githubusercontent.com/108047/221862717-56a5a9cb-1bc8-49ed-a477-5f4d8c823955.png">

I installed **resyntax** after `raco pkg migrate 8.7` .  I initially installed it in the user scope, but I don't expect that to have an impact.

I don't *think* the brew issue affects me but I'm going to read the thread anyway. Thanks.

**Comment by spdegabrielle** [comment]
unable to reproduce 

1. removed 8.8 packages
2. uninstalled 8.8
3. installed packages in 8.7
4. enabled PLTDRPROFILE
5. installed 8.8
6. raco pkg migrate 8.7
7. run DrRacket from command line

```
% export PLTDRPROFILE="ULTRaMan"
% echo $PLTDRPROFILE
ULTRaMan
% /Applications/Racket\ v8.7/DrRacket.app
zsh: permission denied: /Applications/Racket v8.7/DrRacket.app
% /Applications/Racket\ v8.7/DrRacket.app/Contents/MacOS/DrRacket 
PLTDRPROFILE: installing profiler
% /Applications/Racket\ v8.8/DrRacket.app/Contents/MacOS/DrRacket

PLTDRPROFILE: installing profiler
```

**Comment by jbclements** [comment]
By the way, I had this problem myself; turned out I'd installed the x86_64 version of DrRacket, rather than the ARM version. No idea if this was your problem, but I noticed it because editing seemed very sluggish.

**Comment by spdegabrielle** [comment]
ROTFL @jbclements you nailed it.  Yes I am running the intel version.

I have to be honest - it is quite zippy now so I assume the speed problem was an initial optimisation phase. Who knows? 

It is so fast I have no need to switch to switch to the Apple Silicon version but I am anyway.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/108047/224585413-6814fe09-e359-416d-b55b-0d9b4e9a2bf9.png">

**Comment by spdegabrielle** [comment]
My apologies to everyone who wasted their time!
