### ISSUE TITLE
I can't open my previous file ,error loading the file (read-from-file-failed)

### ISSUE THREAD

**Issue by shenxs** [racket/drracket#61]
When I open my file ,Dr racket told me as below

`在读取/home/richard/桌面/TheGame.rkt时出现错误.
insert-file in text%: error loading the file (read-from-file-failed)`

all my code are lost ,what can I do now?
I use Drracket 6.5 on ubuntu 16.04lts
I find the same issue here
http://lists.racket-lang.org/users/archive/2011-October/048596.html

But it doesn't help.

**Comment by rfindler** [comment]
Try posting on the racket-users mailing list to see if they can help you.

**Comment by rfindler** [comment]
I'm going to close this issue as it isn't really actionable in its current form.

But please do try to get some help on the mailing list. There are friendly people there and that's what that forum is intended for. Here's a link to the place:

https://groups.google.com/forum/#!forum/racket-users
