### ISSUE TITLE
Update "DrRacket support for #lang-based Languages" documentation?

### ISSUE THREAD

**Issue by greghendershott** [racket/drracket#641]
Opening a separate issue about something discussed on #634 but which is more general; prompted by today's https://github.com/greghendershott/racket-mode/issues/668.

- IIUC, ever since the addition of [expeditor](https://docs.racket-lang.org/expeditor/index.html), it's better if a lang can assume just a [color-textoid%](https://docs.racket-lang.org/syntax-color/color-textoid.html) interface, not a full `text%`, for things like [drracket:indentation](https://docs.racket-lang.org/tools/lang-languages-customization.html#%28elem._drracket~3aindentation%29), [drracket:range-indentation](https://docs.racket-lang.org/tools/lang-languages-customization.html#%28elem._drracket~3arange-indentation%29), and [drracket:grouping-position](https://docs.racket-lang.org/tools/lang-languages-customization.html#%28elem._drracket~3agrouping-position%29). That way, it will work with expeditor, as well as tools like the back end support for `racket-hash-lang-mode`.

- However [DrRacket support for #lang-based Languages](https://docs.racket-lang.org/tools/lang-languages-customization.html) still talks about `text%` or `racket:text%`.

  - On the one hand, its advice literally satisfies its title -- making langs work in DrRacket :smile:. And some of the items are in fact only intended to work in DrRacket, like [drracket:toolbar-buttons](https://docs.racket-lang.org/tools/lang-languages-customization.html#%28elem._drracket~3atoolbar-buttons%29) or [definitions-text-surrogate](https://docs.racket-lang.org/tools/lang-languages-customization.html#%28elem._definitions-text-surrogate%29). (Some of these may indeed need a full `text%`.)

  - On the other hand, the advice prevents other items as mentioned above from working in expeditor or other tools.

---

So it seems like the page needs to be updated, or split, or something?

Although I was tempted to make a PR, I wanted to ask first and see what ideas people had?  How to title, organize, etc.?  I'm also fine deferring if someone else like @rfindler prefers to draft it instead.

**Comment by rfindler** [comment]
I think it would be great to use `color-textoid<%>` in any place where that would work, in preference to `text%`! I'm not sure which ones make sense or how hard it would be to get everything lined up properly (maybe just a matter of adjusting the docs and maybe some checks for some other functionality?). I'd be delighted if you're interested in making a PR. I can also try to jump in an help out in places where my experience might make stuff go faster.

**Comment by greghendershott** [comment]
Closed by merge of #642.
