### ISSUE TITLE
Wrong background color for recycling symbol.

### ISSUE THREAD

**Issue by soegaard** [racket/drracket#644]
This screenshot is from DrRacket 8.10 [cs] on macOS using the "Tol's White on Black" theme.

<img width="138" alt="image" src="https://github.com/racket/drracket/assets/461765/5f3b6f2f-1d48-42a5-b14e-80dd59809d81">

It shows tha the background color of the recycling symbol doesn't match the panel color.

**Comment by rfindler** [comment]
It's also true in black-on-white mode:

<img width="137" alt="Screenshot 2023-09-24 at 8 15 51 PM" src="https://github.com/racket/drracket/assets/399024/5a3c63e4-a0d3-4d3c-882b-abc5f2b6d035">

It is somewhat intentional, as this place also responds to clicks (triggering a GC).

**Comment by soegaard** [comment]
Ah! It's the black outline that makes it look good in light mode.
Maybe add a white outline in dark mode?

**Comment by sorawee** [comment]
This is what it looks like now:
<img width="179" alt="Screenshot 2023-10-07 at 10 03 53 AM" src="https://github.com/racket/drracket/assets/9099577/eb083452-59f6-428e-9e54-87a8057b509d">

The switch from white to black or black to white still doesn't happen immediately -- it only switches when a new window is created. But I think that's a separate issue.

**Comment by rfindler** [comment]
I agree! Thank you.
