### ISSUE TITLE
Gtk issue on close-tab

### ISSUE THREAD

**Issue by Metaxal** [racket/drracket#645]
To reproduce:
1. Open DrRacket from the command line to see the error port outputs in the console.
2. Open a new tab.
3. Close the tab (either from the menu or with a keyboard shortcut)

The following error message is displayed in the console:
```
Gtk: gtk_notebook_get_tab_label: assertion 'list != NULL' failed
```

While the tab does close and the message seems innocuous, it get displayed on the error port which breaks some tests (such as quickscript-test).

Related: https://racket.discourse.group/t/gtk-gtk-notebook-get-tab-label-assertion-list-null-failed/2373

**Comment by Metaxal** [comment]
The error appears as far as racket -7.5.0.3 (I haven't checked further), so it seems likely that  this is a gtk-only issue.

Strangely, none of the tests drracket-test fail with this error, even though it appears as soon as a tab is closed — which likely means that no single test closes a tab.

**Comment by mflatt** [comment]
I haven't yet been able to replicate this error. If it's a question of suppressing a message that's due to an inconsistency in the library, I think you can do that by running with the `PLTSTDERR` environment variable set to `none`.

**Comment by Metaxal** [comment]
Thanks, I was looking for a way to suppress this error on DrDr, not just locally. For now I just remove the failing tests.
