### ISSUE TITLE
DrRacket leaves bad whitespace on reindent

### ISSUE THREAD

**Issue by florence** [racket/drracket#65]
Start with the file

```
#lang racket
(begin-for-syntax

1)
```

Select everything and hit "tab"

You get
```
#lang racket
(begin-for-syntax
  
  
  1)
```
Where every line has two spaces at the beginning.

I would expect only the line with the 1 to get indentation.

**Comment by rfindler** [comment]
That's not how it works mostly because hitting "return" needs to set you up
for typing and that just does "indent this line".

**Comment by stamourv** [comment]
Right, that makes sense when editing. But in this case, it's about reindenting, which I'd assume works differently, no?

**Comment by rfindler** [comment]
So: the change is that when someone asks for something to be indented and they are asking for more than one line to be indented, if any any of the lines are entirely whitespace, then do not change them.

Do I have that right?

Or maybe it is better to say "if you are indenting a line and you aren't indenting because you just hit return (ie you hit tab or cmd-i (or maybe another way)), and the line is entirely whitespace then don't change the lime"?

**Comment by rfindler** [comment]
After some offline discussion, we are doing something closer to what emacs does:

- if you indent a single line, you add leading whitespace

- if you are indenting multiple lines, you don't modify lines that are all whitespace

**Comment by elibarzilay** [comment]
If you're dealing with this, it would really be nice to add another Emacs-ism: what it does on enter (more accurately, the `newline-and-indent` function) is:

1. Delete horizontal spaces (and tabs)
2. Insert a newline
3. Indent as usual (regardless of whether the current line has non-space chars or not)

The only new thing here is the first step of deleting horizontal spaces -- but it makes much nicer files as a result.  It means that if you type "`foo `" and hit enter, the extra space is deleted; if you hit enter at a beginning of a line or anywhere in the indentation of the line, then that line moves down and the previous line is left empty; and if you hit enter in the middle of a line in some block of spaces, they get removed so again you're not left with those dangling spaces that are a sign of such edits...

**Comment by rfindler** [comment]
If I am understanding correctly, the current DrR does this already, thanks
to Max New.

**Comment by elibarzilay** [comment]
Oh, really??  I haven't tried it yet (I'll get to that before the semester), but that thing has been bugging me for *so* long I *definitely* owe him a beer or something whenever he's around.

**Comment by rfindler** [comment]
@maxsnew you are owed a beer ;)
