### ISSUE TITLE
The indentation guide covers the #lang line

### ISSUE THREAD

**Issue by shhyou** [racket/drracket#650]
- **Version:** Racket: 8.11.0.3, DrRacket racket/drracket@2c9c89446fe672e21, GUI racket/gui@a4f3070aeb8fe986d
- **Description:** the indentation guide lines covers the `#lang` line when the option "_Always show #lang line in the Module language_" is enabled.
- **Expected behavior:** it might be more intuitive if the `#lang` line overlays the indentation guide lines.
![Screenshot of #lang line covered by the indentation guides](https://github.com/racket/drracket/assets/1910898/92ed9378-cd8c-4b79-9d1e-c1b49534fb6e)

**Comment by shhyou** [comment]
Potential fix: move L560 to L544-L545.
https://github.com/racket/drracket/blob/0e9afeb0da1d7fbbf010bbdaf3515a2910fd56e7/drracket/drracket/private/unit.rkt#L542-L562

**Comment by rfindler** [comment]
Oh, that's a great idea! I was thinking of changing the mixin so that the first-line mixin knew about the indent-guides mixin explicitly, but I like this idea better.

**Comment by rfindler** [comment]
Thanks, I've pushed the fix [here](https://github.com/racket/drracket/commit/edc80d6206c1457b26ae3525a103202310ac205e)
