### ISSUE TITLE
Theme selection buggy

### ISSUE THREAD

**Issue by sorawee** [racket/drracket#652]
After scrolling, UI elements overlapped everywhere.

<img width="964" alt="Screenshot 2023-12-11 at 9 29 32 PM" src="https://github.com/racket/drracket/assets/9099577/ed5ae574-ab22-48bb-90a7-24529b324123">

**Comment by rfindler** [comment]
I'm not seeing this. Could it be specific to a particular version of macOS? I'm on 13.6.1 (22G313).

**Comment by sorawee** [comment]
I'm on 14.1.2

**Comment by sorawee** [comment]
I can't reproduce the problem with the snapshot installation. It's only the build-from-source installation that has this problem.

**Comment by rfindler** [comment]
The snapshot is built on a different version of the OS, I think. Not sure how that could matter, tho.

**Comment by sorawee** [comment]
Something is seriously messed up with my installation. Here's another weird UI

<img width="964" alt="Screenshot 2023-12-12 at 8 30 16 PM" src="https://github.com/racket/drracket/assets/9099577/572e0a92-032f-41d7-afe1-22b4f07d0f43">

**Comment by sorawee** [comment]
Fixed by https://github.com/racket/gui/pull/326
