### ISSUE TITLE
Automatic Theme Sync in DrRacket

### ISSUE THREAD

**Issue by lemorage** [racket/drracket#655]
### Description
I am using DrRacket version 8.11.1 on macOS. It appears that the themes in DrRacket are automatically synced with the macOS light/dark mode. When I open DrRacket during the day, it automatically switches to the white theme, and I need to manually switch it to the dark theme. The next day, it reverts to the white theme again.

I reckoned that it might be due to the global light/dark mode setting, and DrRacket seems to follow this setting automatically. I would like to know if there is a way to decouple DrRacket's theme from the system-wide setting.

### System Information
- DrRacket Version: 8.11.1
- Operating System: macOS Sonama 14.1.2

**Comment by rfindler** [comment]
There isn't currently, unfortunately.

**Comment by lemorage** [comment]
Ah, alright. That's fine.
