### ISSUE TITLE
Internal Error when searching

### ISSUE THREAD

**Issue by howell** [racket/drracket#67]
I get the following error:

```
do-search method in ...ork/private/text.rkt:1136:2: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 2
  given: 3
  arguments...:
   (object:...engine/test-tool.scm:22:6 ...)
   70
   'eof
```

I can reproduce this by:

1. Opening DrRacket
2. Cmd-F to open search
3. Type 'r'
4. Press Enter

Although I think it happens every time I execute a search.

I'm running racket 6.6.0.2 on OSX 10.8.4

**Comment by rfindler** [comment]
Please update DrRacket.
