### ISSUE TITLE
sub-range-binders give misaligned arrows when the id uses |…|

### ISSUE THREAD

**Issue by jsmaniac** [racket/drracket#68]
```racket
#lang racket
(struct s (a))
|||s-a|||
\s\-\a

|||list|||
\l\i\s\t
```

In DrRacket, the file above shows an arrow from `s` to the first pipe and the first `\`, and an arrow from `a` to the third pipe and the second `\`. In other words, the offsets do not take into account escapements with `|…|` or with `\`, which do not contribute to the actual length of the identifier, once it is `read`.

Without the `'sub-range-binders`, however, there is no problem: `racket` in `#lang racket` points to the whole `|||list|||` and to the whole `\l\i\s\t` (if it had the same problem, it would highlight only the first four characters).

**Comment by rfindler** [comment]
This is an understood shortcoming in the way information flows around in the system. 

In particular, which of the precise spellings that an identifier used is lost by the time it gets to the point where arrows are decided. The ranges are kept, tho, which is why arrows to the entire identifier work out.

**Comment by jsmaniac** [comment]
Sorry, I didn't know this is a known issue.

This kind of problem (loosing the original spelling) happens in other places too. For example scribble has to resort to comparing the `syntax-span` with hard-coded values to distinguish between `#t` and `#true`, and it can't distinguish between `#t` and `#T`.

Would it be possible to attach a `original-spelling` syntax-property in the reader, which would contain a string representation of the original atom as written in the source file?

I don't think it would affect the memory consumption much, as the extra memory needed will roughly be equal to the source file's length plus one pointer per syntax object with the property. It would even be possible to attach the property only if the atom is not written in its canonical form, i.e. when `(string-equal? (write (read (open-input-string atom-str))) atom-str)` is false.

**Comment by rfindler** [comment]
That sounds like a lot of extra memory, but perhaps if it were put on only when the original spelling wasn't some canonical, normal way to spell it that sounds like it would be great!

Assuming @mflatt agrees, Pull requests welcome!
