### ISSUE TITLE
Alt+Q reflow in drracket looses characters

### ISSUE THREAD

**Issue by LeifAndersen** [racket/drracket#69]
If I'm in DrRacket and I reflow the following line with the Alt+Q option:

    and lapply. The first half of @figure-ref{looping-constructs-sample}.

It turns into:

    and lapply. The first half of @figure-ref{
     ooping-constructs-sample}.

Note how the figure-ref name has lost the leading `l` in looping, and is now ooping.

**Comment by LeifAndersen** [comment]
For reference, the whole file for this bug is:

    #lang scribble/base

    @(require scriblib/figure)

    and lapply. The first half of @figure-ref{looping-constructs-sample}.

**Comment by rfindler** [comment]
That's correct. You should not write strings inside {} as they will get
reflowed. Write @figure-ref["looping-constructs-sample"]. Or, perhaps,
write @figure-ref["fig:loop-ex"] ...

**Comment by rfindler** [comment]
Also: wrong repo. The code is in the gui repo.
