### ISSUE TITLE
Context menu copy grabs wrong thing

### ISSUE THREAD

**Issue by toddobryan** [racket/drracket#694]
I've been using comment boxes in files for student assignments.

If you right-click and copy near a comment box, it seems to grab the contents of the comment box, not the selected text (video below).

Ctrl-C does seem to work.

https://drive.google.com/file/d/1hQwIv4CqqjjuJQrLnUKittQh0TtHFPBp/view?usp=sharing is a link to a video of the bug.

**Comment by rfindler** [comment]
Wow, that's unexepected! 

I tried with just a small example that kind of looks like your file but that didn't reproduce the bug. Do you mind sharing a file and the specific region you're copying? (The smaller the file the better, but any reasonable sized file will be totally fine.)

**Comment by toddobryan** [comment]
I'll send you the file directly, Robby. I'm on Linux.

**Comment by rfindler** [comment]
It looks like the missing piece for me was that the window has to be scrolled. It was a coordinate system bug.
