### ISSUE TITLE
Scheme code mistakenly evaluated?

### ISSUE THREAD

**Issue by esdoppio** [racket/drracket#70]
I was expecting

```scheme
(quote (quote cons))
```

to yield `(quote cons)`, but instead

![image](https://cloud.githubusercontent.com/assets/18070858/18261195/a05e9bb4-7427-11e6-8232-bf0d3b295f34.png)

**Comment by jbclements** [comment]
> On Sep 5, 2016, at 8:52 PM, Vince Fitz <notifications@github.com> wrote:
> 
> I was expecting
> 
> (quote (quote cons))
> to yield (quote cons),

Short answer: your guess was right, it *did* evaluate to that. specifically, it evaluated to a list containing two elements. The first is the symbol q u o t e, and the second is the symbol c o n s.

A good chunk of the confusion stems here from the “scheme” language level that you’re using, which essentially strips one layer of quoting from the printed answer. If you try running this program in the #lang racket language, you’ll see that

#lang racket

(quote (quote cons))

evaluates an answer that’s printed as

‘’cons

if you try thinking through this slowly, you’ll see that this is actually consistent, and that no evaluation is occurring.

John

P.S.: Twenty years of experience tells me that I did not explain this clearly. Sorry!

P.P.S.: Okay with you if I close this issue?

**Comment by esdoppio** [comment]
Oh, I get it. So whenever a `'` appears in the output, think of it as a level of `(quote …)`, right?

Thanks, professor. Pray close it.

**Comment by jbclements** [comment]
> On Sep 5, 2016, at 9:39 PM, Vince Fitz <notifications@github.com> wrote:
> 
> Oh, I get it. So whenever a ' appears in the output, think of it as a level of (quote …), right?

Yep, that’s right.

John Clements
