### ISSUE TITLE
Unchecking the options under `(define ...)' breaks DrRacket

### ISSUE THREAD

**Issue by leafac** [racket/drracket#73]
**STEPS TO REPRODUCE**

1. On DrRacket, on the upper-left, there is a `(define ...)` drop down menu. Under it, there are options regarding what kinds of definitions to show: `(module ...)` or `(define ...)`. **Uncheck both**.

2. Click on the `(define ...)` drop down menu again.

**CURRENT BEHAVIOR**

DrRacket fails with the following **DrRacket Internal Error**:

```
=: contract violation
  expected: number?
  given: #f
  argument position: 2nd
  other arguments...:
   +inf.0
  context...:
   /Applications/Racket v6.6/share/pkgs/drracket/drracket/private/get-defs.rkt:45:2: find-next
   /Applications/Racket v6.6/share/pkgs/drracket/drracket/private/get-defs.rkt:36:0: get-definitions
   /Applications/Racket v6.6/share/pkgs/drracket/drracket/private/unit.rkt:1098:6: fill-popup method in func-defs-canvas%
   /Applications/Racket v6.6/share/pkgs/gui-lib/mrlib/name-message.rkt:125:4: on-event method in name-message%
   /Applications/Racket v6.6/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /Applications/Racket v6.6/collects/ffi/unsafe/atomic.rkt:72:13
   /Applications/Racket v6.6/share/pkgs/gui-lib/mred/private/wx/cocoa/window.rkt:811:4: dispatch-on-event method in window%
   /Applications/Racket v6.6/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:454:6
   /Applications/Racket v6.6/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:505:32
   /Applications/Racket v6.6/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:653:3
```

Closing and reopening DrRacket does not make the problem go away.

**EXPECTED BEHAVIOR**

DrRacket does not fail, but shows an empty list of definitions and the same options as before.

**WORKAROUND**

Go to `Preferences`, click on `Revert All Preferences to Defaults` and restart DrRacket.

**INITIAL INVESTIGATION**

The stack trace points to `drracket/private/get-defs.rkt`. I believe the issue is on line 72, which reads `(when (= +inf.0 smallest-pos)`. `smallest-pos` was initialized to `#f` on line `65` and, if `filled-in-positions` is empty, then `smallest-pos` is not changed. If this is correct, than it should suffice to change line 72 to `(when (equal? +inf.0 smallest-pos)`. But I do not know the code base enough to be confident that it solves the issue. If you would like, I can send a pull request with that change.

-----

If there is anything I can do to help fixing this, please let me know.

Thank you for DrRacket, it is a great tool.

**Comment by leafac** [comment]
Thank you for the fix, @rfindler.

**Comment by rfindler** [comment]
Thanks for finding the problem! And I think what you suggested would also
have been fine. (I somehow saw that only after finding the fix I pushed.)
