### ISSUE TITLE
mysterious error while making #langs in DrRacket

### ISSUE THREAD

**Issue by mbutterick** [racket/drracket#78]
Sorry this report is a vague, but I'm looking for info that would help me narrow it down. 

I'm making small DSLs in DrRacket that use both a reader and expander in separate modules. Whenever I update a language's reader or expander and switch to a source file that uses the language, as DrRacket does its background expansion, it throws an error like the one below (though the source file will otherwise work as expected.) Once I recompile the file, the error disappears.

I'm afraid it's not even clear to me from the trace which expression is actually throwing the error. Do you have a guess?

```racket
internal error: -: contract violation
  expected: number?
  given: #f
  argument position: 1st
  other arguments...:
   0
  context...:
   /Users/MB/git/racket/racket/share/pkgs/drracket-tool-lib/drracket/private/syncheck/traversals.rkt:819:14: for-loop
   /Users/MB/git/racket/racket/share/pkgs/drracket-tool-lib/drracket/private/syncheck/traversals.rkt:674:10: for-loop
   /Users/MB/git/racket/racket/share/pkgs/drracket-tool-lib/drracket/private/syncheck/traversals.rkt:668:6: for-loop
   /Users/MB/git/racket/racket/share/pkgs/drracket-tool-lib/drracket/private/syncheck/traversals.rkt:636:4: annotate-variables
   /Users/MB/git/racket/racket/share/pkgs/drracket-tool-lib/drracket/private/syncheck/traversals.rkt:48:14: core49
   /Users/MB/git/racket/racket/share/pkgs/drracket/drracket/private/syncheck/online-comp.rkt:43:0: build-trace
   .../more-scheme.rkt:261:28
   /Users/MB/git/racket/racket/share/pkgs/drracket/drracket/private/syncheck/online-comp.rkt:91:5: loop
```

**Comment by mbutterick** [comment]
Actually, ignore the part about the error disappearing after recompile.

1) It is called a "Check Syntax Error Message".
2) It seems to recur whenever the background expansion is triggered. So even though the source file runs fine in DrRacket, if I add a character to the definitions window, background expansion is triggered again, and the error reappears.
3) If I disable background expansion, the error stops.

**Comment by rfindler** [comment]
I think the commit I just pushed fixes that, but there may be other errors still lurking.

Is it possible your new reader is not putting source locations in enough places, btw? (It doesn't have to, but it is probably preferable to.)

**Comment by mbutterick** [comment]
Thanks, that seemed to work. I will post back if it reappears.

You're right — my reader is definitely not putting any source locations. But this is for a simplified language-tutorial project, so the omission is deliberate.

**Comment by rfindler** [comment]
having no source locations anywhere is definitely a shortcoming of the current test suite!
