### ISSUE TITLE
C:e toogles the interactive window but the cursor remains in the definitions window

### ISSUE THREAD

**Issue by triklsbg** [racket/drracket#85]
I would expect the cursor in the interactive window after pressing C:e in the def window.

Platform: archlinux 64bit drracket 6.7, german

**Comment by rfindler** [comment]
That keystroke move the focus only when the window with the focus goes away. Consider adding your own keystrokes if you want different behavior. Here are the docs: 

  http://docs.racket-lang.org/drracket/Keyboard_Shortcuts.html#%28part._defining-shortcuts%29
