### ISSUE TITLE
DrRacket crashes in macOS 10.12.2

### ISSUE THREAD

**Issue by LinghanX** [racket/drracket#86]
DrRacket crashes under macOS 10.12.2.

DrRacket seems unable to launch under the latest update of macOS 10.12.2

**Comment by mflatt** [comment]
Thanks for the report! A repaired version will be available as tomorrow's snapshot build. 

Meanwhile, if you'd like to manually patch your installation, you could edit
```
   share/pkgs/gui-lib/mred/private/wx/cocoa/queue.rkt 
```
and delete the
```
   #:protocols (NSApplicationDelegate)
```
part of line 55.
