### ISSUE TITLE
Syntax objects have srcloc before background expansion finishes, but not after

### ISSUE THREAD

**Issue by jsmaniac** [racket/drracket#88]
Racket version: 6.7.0.4
Worth noting, I have `populate "compiled" folders` disabled in the language settings (Ctrl+L)

```racket
#lang racket (begin-for-syntax (sleep 1)) #'a
```

If I paste this program in an already saved file in DrRacket, and press `F5` immediately, I see

```
#<syntax:/tmp/file.rkt:1:44 a>
```

If instead I wait a couple of seconds so that the background expansion finishes (lower-right icon turns green), then I see:

```
#<syntax:1:44 a>
```

In the second case, the source location is hidden, but shown in the first case. If I click on the arrow icon next to the syntax object, I can see that in the first case the `Source` is `#<path:/tmp/a.rkt>`, whereas in the second case the `Source` is `".../tmp/a.rkt"`.

**Comment by rfindler** [comment]
Until I figure out a fix, you could turn debugging back on (you'll see the proper behavior I believe).

**Comment by jsmaniac** [comment]
Thanks, I actually prefer the notation without the source file, as it clutters a bit the interface otherwise :) . The wrong `Source` seems more of a potential issue, so I'll keep the workaround in mind.

**Comment by rfindler** [comment]
Ah. Well that's an issue for another repo :)

**Comment by rfindler** [comment]
Thanks, @mflatt
